Migrate DurableTask.ServiceBus ServiceBus SDK from Microsoft.Azure.ServiceBus to Azure.Messaging.ServiceBus
Azure/durabletask pull request #1014
Opened 2023-12-08 17:25 UTC by NateLehman

## Validation strategies for .NET Core version
It has come to my attention that the .NET Core version of this library needs additional validation. This section describes validations performed manually. 
 
### Leveraging a real world prod service
Without revealing much about our internal design, my team uses DTF ServiceBus for running workflows in a .NET Core project. I've locally sideloaded this new version into a worker service running in a dev environment that consumes real world application orchestrations.

The tasks and orchestrations consumed by the worker running with the sideloaded library did not produce unhandled exceptions and did not behave in any way that suggested issues. Additionally, the worker was running in concert with other worker instances that were running the current stable version without Azure.Messaging.ServiceBus; I consider this a testament to its compatibility.

### Running DurableTask.ServiceBus.Tests project
I also set up live ServiceBus and AzureStorage resources in my own Azure subscription and added their connections strings to the project. This allowed me to run the DurableTask.ServiceBus.Tests(netcoreapp3.1) project against real world resources and validate those scenarios. I am attaching a VSTest overview screenshot as proof of these results:
![image](https://github.com/Azure/durabletask/assets/9384649/fc3ffe36-596f-4d59-80cc-093386560270)

**NOTE**: All of the failing tests in this image are *ALSO* failing in the previous stable version (when I switch to `main` branch).

2023-12-08 17:30 UTC, NateLehman commented on src/DurableTask.ServiceBus/ServiceBusOrchestrationService.cs
> +             * This will actually need to be a breaking change. We can't use
Remove

2023-12-08 17:30 UTC, NateLehman commented on src/DurableTask.ServiceBus/ServiceBusOrchestrationService.cs
> +             * try to test this prior to making an actual change.
remove note

2023-12-08 17:33 UTC, cgillum reviewed
A couple administrative comments (haven't looked at the core implementation quite yet):

2023-12-08 17:33 UTC, cgillum commented on src/DurableTask.ServiceBus/DurableTask.ServiceBus.csproj
> +    <!-- <TargetFrameworks>netstandard2.0;net462</TargetFrameworks> -->
Can this line be removed?

2023-12-08 17:33 UTC, cgillum commented on src/DurableTask.ServiceBus/DurableTask.ServiceBus.csproj
> +    <PackageReference Include="Azure.Messaging.ServiceBus" Version="7.16.2" />
Since we're making a major version change to this dependency, I think we also need to consider making a major version change to this particular package (i.e. set `<MajorVersion>3</MajorVersion>` and `<MinorVersion>0</MinorVersion>`.

2023-12-08 17:33 UTC, cgillum commented
/azp run

2023-12-08 17:37 UTC, NateLehman commented on src/DurableTask.ServiceBus/Common/Abstraction/ServiceBusAbstraction.cs
> +        [Obsolete]
remove functions marked as obsolete (I did this as a way of co-existing the libraries while working on the conversion

2023-12-27 20:26 UTC, NateLehman commented on src/DurableTask.ServiceBus/DurableTask.ServiceBus.csproj
> +    <PackageReference Include="Azure.Messaging.ServiceBus" Version="7.16.2" />
I've set our version to 3.0.0 --- let me know if that's correct, or if we need to do something else with the minor version, etc

2024-01-02 17:50 UTC, NateLehman commented
/azp run

2024-01-02 18:21 UTC, NateLehman commented on src/DurableTask.ServiceBus/Common/Abstraction/ServiceBusAbstraction.cs
> +            if (sessionState == null)
this looks a bit weird, but it prevents InvalidArgumentExceptions and retains compatibility

2024-01-04 20:47 UTC, davidmrdavid commented
/azp run

2024-01-04 20:57 UTC, davidmrdavid commented
/azp run

2024-01-04 20:58 UTC, davidmrdavid commented
/azp run

2024-01-09 17:43 UTC, NateLehman commented
There's now a successful pipeline run associated with this PR.

![image](https://github.com/Azure/durabletask/assets/9384649/ba840593-2ca5-4468-9e73-8b2bf3ff4272)

I think there are some details about the GitHub<->Azure DevOps integration that I'm not familiar with. It looks like this is being blocked from merging based on a previous run.

2024-03-19 20:54 UTC, sjiherzig commented
/azp run

2024-03-19 20:56 UTC, sjiherzig commented
@davidmrdavid , @cgillum Is there anything else we should do before we can merge this PR?

2024-03-21 04:25 UTC, cgillum commented
/azp run

2024-03-21 21:44 UTC, cgillum approved these changes
Everything looks good from my perspective. I confirmed that the CI is executing both the Azure Storage and Service Bus tests in a distributed way. I think we should be good to merge this now.

2024-03-21 21:54 UTC, cgillum requested changes
Ah, I think I mispoke. It seems the tests are actually still just running the `net462` variants, according to the logs:

> Source filter: **\bin\Debug\net462\DurableTask.AzureStorage.Tests.dll,**\bin\Debug\net462\DurableTask.ServiceBus.Tests.dll,**\bin\Debug\net462\DurableTask.Core.Tests.dll,**\bin\Debug\net462\DurableTask.Emulator.Tests.dll,!**\obj\**

We'll need to update the pipeline to run the .NET Core variant of these libraries.

2024-04-17 21:58 UTC, cgillum approved these changes

2024-04-17 21:59 UTC, cgillum commented
/azp run

2024-04-19 22:42 UTC, cgillum commented
I manually ran the `DTFx Build & Run Tests (ServiceBus)` pipeline and confirmed that it's also green. Merging.

2024-04-19 22:43 UTC, merged