Merge main into azure-storage-v12
Azure/durabletask pull request #1077
Opened 2024-04-25 07:00 UTC by nytian

2024-05-08 20:22 UTC, bachuv approved these changes

2024-05-09 00:12 UTC, davidmrdavid approved these changes

2024-05-09 00:16 UTC, davidmrdavid requested changes
My apologies, I would actually like to inspect the commit history a bit closer - I notice the merge commit is rather large (https://github.com/Azure/durabletask/pull/1077/commits/d8863e1aa40b78c83088bc6f530cca4131ac6598) but I'd expect it to be only the conflict resolution diff. I'd like to triple check why that is, so let's please hold off on this for a bit.

2024-05-17 23:08 UTC, davidmrdavid approved these changes
After reading up a bit more on how merge commits represent diffs, I'm no longer concerned. Looks good, although in the future it would be good to keep branches up to date with each often more often so we don't have large PRs like this one, but that's everyone's responsibility :). Thank you for handling the difficult merges!

2024-05-17 23:30 UTC, merged