Remove net462 TFM
Azure/durabletask pull request #1125
Opened 2024-07-03 19:15 UTC by bachuv

Removed .NET Framework 4.6.2 TFM and upgraded DurableTask.Core version to 3.0.0.

2024-07-04 14:35 UTC, cgillum commented on src/DurableTask.AzureStorage/DurableTask.AzureStorage.csproj
>      <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="2.2.0" />
The expression `Condition="'$(TargetFramework)' == 'netstandard2.0'"` is always going to be true now, so let's consolidate all package references to be in the same `<ItemGroup>` above.

2024-07-04 14:35 UTC, cgillum commented on src/DurableTask.Core/DurableTask.Core.csproj
>    <ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.0'">
Similar comment as in the other csproj file, let's consolidate all the `<PackageReference .../>` nodes to be in the same `<ItemGroup>`

2024-07-10 20:21 UTC, davidmrdavid requested changes
LGTM but let's make sure the GitHub actions are running on all PRs, as this has not had the validation executed on it :)

2024-07-11 09:14 UTC, nytian approved these changes
Thanks for the PR! Left a small question :)

2024-07-11 09:14 UTC, nytian commented on src/DurableTask.ServiceBus/Tracking/AzureTableOrchestrationHistoryEventEntity.cs
> -#if NETSTANDARD2_0
Just wondering can we update the code in ServiceBus? Doesn't this belong to other teams?

2024-07-11 20:29 UTC, davidmrdavid commented on src/DurableTask.ServiceBus/Tracking/AzureTableOrchestrationHistoryEventEntity.cs
> -#if NETSTANDARD2_0
ServiceBus is not actively maintained. It should be ok. I think you're thinking of ServiceFabric, which is maintained by another team.

2024-07-11 20:29 UTC, davidmrdavid approved these changes
I'll approve since the GitHub actions should run as soon as we try to merge to main. Let's open that PR asap

2024-07-11 20:37 UTC, merged