Poison message handling for DT.AS V2
Azure/durabletask pull request #1130
Opened 2024-07-09 19:17 UTC by bachuv

This PR adds poison message handling for DurableTask.AzureStorage V2. There's a new `PoisonMessageDeuqueCountThreshold` setting in `AzureStorageOrchestrationServiceSettings` where the default is set to 20. If a message is dequeued and fails to deserialize more than the number that's set for `PoisonMessageDeuqueCountThreshold`, then it gets added to a new `<TaskHubName>Poison` table in Azure Storage. Customers can go to this table in their storage account and look at these poison messages.

2024-07-09 20:05 UTC, cgillum requested changes
Biggest blocker for me on this PR are the changes to DurableTask.Core. I don't think a case has been made for this yet, and it needs further discussion. At this point, my preference is to change only DurableTask.AzureStorage.

2024-07-09 20:05 UTC, cgillum commented on src/DurableTask.AzureStorage/Messaging/TaskHubQueue.cs
> +        public async Task<bool> TryHandlingDeserializationPoisonMessage(QueueMessage queueMessage, Exception deserializationException)
It looks like there's a lot of redundancy between these two methods. Is it possible to refactor them to share some logic?

2024-07-09 20:05 UTC, cgillum commented on src/DurableTask.Core/History/HistoryEvent.cs
> +        public string PoisonGuidance { get; set; } = "";
I'm not comfortable with adding these properties to every DTFx history event, especially if we don't have a plan or design for whether/how to implement poison message handling for other backend providers. For the purposes of this PR, I'd prefer we make changes only to DurableTask.AzureStorage unless we can get broad agreement from across the team that this is the right approach.

2024-07-10 19:56 UTC, davidmrdavid commented on src/DurableTask.AzureStorage/Messaging/ControlQueue.cs
> +            this.settings.Logger.MessageFailure(
I believe this overload is only called in cases where there's an exception, as you can see by the comment in line 193: https://github.com/Azure/durabletask/blob/934a5b673c52ee217df3de249498f982ef72652a/src/DurableTask.AzureStorage/Messaging/ControlQueue.cs#L192 . In that case, doesn't that mean the exception will never be null, @cgillum ?

2024-07-10 20:03 UTC, davidmrdavid commented on src/DurableTask.Core/History/HistoryEvent.cs
> +        public string PoisonGuidance { get; set; } = "";
Makes sense. Just to add more context here (may be obvious) - the reason for the DTFx.Core change here is solely that it allows us to _easily_ fail the function (activity or orchestrator) with the poison message. In the activity/orchestrator dispatchers, we are checking if `isPoison` is true and, if so, we're replacing the history event of the poison message with a failure event.

I assume that if instead of doing this, we replace the **message** itself with a failure event in the DTFx.AS level, we should be able to get away without this "isPoison" property. I recall trying to do this, and not finding it to be super obvious, but it's worth trying again. @cgillum if you have suggestions, I'm all ears!

2025-01-23 08:18 UTC, Kencdk commented
Instead of having a "one-size fits no-one" implementation; could this be extended to include an error handler which can be defined by developers instead, potentially with this as the default implementation?

That would allow developers to easily add new metrics, logs and store messages where they see fit, instead of having to rely on table storage and updates to the main library in case we would like more data readily available.

2026-06-05 04:14 UTC, closed without merging