Add Check for Lease Ownership Bug in Table Partition Manager
Azure/durabletask pull request #1136
Opened 2024-07-15 19:44 UTC by nytian

This PR addresses a bug reported by customers involving the table partition manager. The issue occurs when a worker is the owner of a partition without claiming the lease. This can happen when a worker restarts or crashes and returns to a healthy state before the lease expires, thus it remains the owner of the partition. In our current logic, the worker only listens to a control queue when it has claimed a lease. Therefore, in the above scenario worker will continue to renew the lease without listening to queue messages.

To resolve this, the PR adds a check to ensure that when a worker reads the partition table and identifies itself as the current lease owner, it verifies if it is actively listening to the queue. If it is not, the worker should initiate the process to start listening to the queue. This ensures that the lease renewal logic only applies when the worker is actively managing the partition.

2024-07-15 19:45 UTC, nytian commented on src/DurableTask.AzureStorage/AzureStorageOrchestrationService.cs
> +        internal bool CheckIfListeningToOwnedQueue(TablePartitionLease partition)
Let me know if you have thoughts about the method naming! :)

2024-07-15 20:09 UTC, davidmrdavid reviewed
Left a small comment. I'd also love to add some test here

2024-07-15 20:09 UTC, davidmrdavid commented on src/DurableTask.AzureStorage/Partitioning/TablePartitionManager.cs
> +
I'm a bit worried about adding more cases to this for-loop, so I'd prefer to re-use the existing `renewedLease` case/boolean to check if we're actively listening to the queue.

Can we use the `renewedLease` variable to enter the if-statement leading to `OnTableLeaseAcquiredAsync`. Then, inside `OnTableLeaseAcquiredAsync`, you could check, somehow, if the queue is already in our listened-to set?

2024-07-15 21:26 UTC, nytian commented on src/DurableTask.AzureStorage/Partitioning/TablePartitionManager.cs
> +
Updated. Let me know if I understood it correctly.

2024-07-15 23:42 UTC, bachuv reviewed
Thanks for fixing this bug! I appreciate how you added comments in the code explaining the changes :)

2024-07-15 23:42 UTC, bachuv commented on test/DurableTask.AzureStorage.Tests/TestTablePartitionManager.cs
> +                    "Not all orchestrations completed successfully!");
Why does it say "Not all orchestration completed successfully"? Shouldn't they all complete successfully?

2024-07-16 00:52 UTC, cgillum commented on test/DurableTask.AzureStorage.Tests/TestTablePartitionManager.cs
> +                    "Not all orchestrations completed successfully!");
This is the error message which will be written to the test logs if `Assert.IsTrue` fails (in other words, we're giving a clear indication of what the problem is: some orchestrations didn't complete).

2024-07-16 00:57 UTC, cgillum approved these changes
LGTM! I appreciate that you added a new test case to cover and validate this scenario.

2024-07-16 15:54 UTC, davidmrdavid requested changes
Just want to make sure this works well for the case when we're supposed to be draining the queue. In that case - shouldn't we renew the lease but stop listening to new messages? I worry this PR may work against that.

2024-07-17 00:02 UTC, davidmrdavid reviewed
I think we want to do the following. If this checks out to you, can you please help me with a test?

2024-07-17 00:02 UTC, davidmrdavid commented on src/DurableTask.AzureStorage/Partitioning/TablePartitionManager.cs
> +                        if (claimedLease || renewedLease)
I _think_ this is what we want:

```suggestion
                        // Ensure worker is listening to the control queue iff either:
                        // 1) worker just claimed the lease,
                        // 2) worker was already the owner in the partitions table and is not actively draining the queue. Note that during draining, we renew the lease but do not want to listen to new messages. Otherwise, we'll never finish draining our in-memory messages.
                        bool isRenewingToDrainQueue = renewedLease & response.IsDrainingPartition
                        if (claimedLease || !isRenewingToDrainQueue)
```

2024-07-17 00:06 UTC, davidmrdavid commented on src/DurableTask.AzureStorage/Partitioning/TablePartitionManager.cs
> +
You did, thanks!

2024-07-18 17:58 UTC, davidmrdavid commented
Closing as it was merged here: https://github.com/Azure/durabletask/pull/1142

2024-07-18 17:58 UTC, closed without merging