Handle poisoned work items by marking them as failed
Azure/durabletask pull request #1175
Opened 2024-11-11 17:32 UTC by ItalyPaleAle

When orchestrations and activity tasks fail with un-retriable errors (by any worker), they should not be abandoned; instead, they should be marked as completed and with state failed.

This is implemented by catching exceptions of type `WorkItemPoisonedException` which can be raised downstream, for example by a persistence store provider. When that happens, instead of abandoning the work item, the dispatcher marks it as completed.

2024-11-11 23:36 UTC, cgillum requested changes
Thanks for this PR @ItalyPaleAle, I like these changes as a first step in helping us deal with poison messages more generally. Some of the cases we normally deal with are on the work item fetch side (failing to deserialize received work items, for example) but my hope is that we can at least borrow some of the ideas here in separate PRs to also address those cases.

I added some comments about things I think we should fix or discuss before merging. They should be pretty minor.

FYI @davidmrdavid since this is a topic you've also spent a lot of time thinking about. Note that the motive in this case is for a different class of poison messages than what you were thinking about, but there might be some common pieces we can consider reusing.

FYI @sebastianburckhardt as well.

2024-11-11 23:36 UTC, cgillum commented on src/DurableTask.Core/Logging/StructuredEventSource.cs
> +                    Details,
Do we need to check for null here? Passing `null` to `WriteEvent` for any parameter will cause the entire log event to be lost. If I'm reading the code correctly, this comes from the `WorkItemPoisonedException.Message` property, which doesn't have any guards against null values.

2024-11-11 23:36 UTC, cgillum commented on src/DurableTask.Core/Logging/StructuredEventSource.cs
> +                    Details,
Same question about null checks.

2024-11-11 23:36 UTC, cgillum commented on src/DurableTask.Core/OrchestrationRuntimeState.cs
> +            return new OrchestrationRuntimeState(this.Events)
I don't think this is technically a deep clone operation. The state of the two objects may potentially be different. For example, if the object being cloned as a set of history events in both the `NewEvents` and `PastEvents` lists, then the cloned object will instead have all the history event objects only in the `PastEvents` list.

I suggest either we carefully document that this is not an exact clone or give this method a different name.

2024-11-11 23:36 UTC, cgillum commented on src/DurableTask.Core/TaskActivityDispatcher.cs
> +                            poisonedException.Message, string.Empty),
We need to also populate the `failureDetails` parameter of the `TaskFailedEvent` constructor since there will be some consumers that use that instead of the (legacy) `reason` + `details` values.

2024-11-11 23:36 UTC, cgillum commented on src/DurableTask.Core/TaskOrchestrationDispatcher.cs
> +            OrchestrationRuntimeState originalOrchestrationRuntimeState = runtimeState.Clone();
I see that you've repurposed this variable to be used only for the new poison message handling logic, which I think is fine given that the previous behavior used `originalOrchestrationRuntimeState` as a reference to the live `runtimeState` object (I don't recall why - the previous implementation seems confusing to me, but I haven't gone back to look at the change history). This is fine, but just confirming that this was your intention, and that you intended to do it in a way that doesn't change existing behavior (per your comment further down)?

2024-11-11 23:36 UTC, cgillum commented on src/DurableTask.Core/TaskOrchestrationDispatcher.cs
> +                    instanceState);
Do we need to update `instanceState` to also reflect the fact that this instance is now in a failed state?

2024-11-11 23:54 UTC, ItalyPaleAle commented on src/DurableTask.Core/OrchestrationRuntimeState.cs
> +            return new OrchestrationRuntimeState(this.Events)
Do you reckon the issue is with the description/comment only, or should the behavior be changed too?

2024-11-11 23:58 UTC, ItalyPaleAle commented on src/DurableTask.Core/TaskOrchestrationDispatcher.cs
> +            OrchestrationRuntimeState originalOrchestrationRuntimeState = runtimeState.Clone();
In the existing code, `originalOrchestrationRuntimeState` is pointing to the same memory as `runtimeState`, so by the time it is used (when `workItem.RestoreOriginalRuntimeStateDuringCompletion` is true), it is pointing to the updated state.

To me that smells a bit like it could _potentially_ be a bug in the existing implementation. However, I didn't want to alter the behavior in this PR as I'm not fully understand what the purpose (or intention) were, or whether fixing the bug (if it is) would break any existing user.

However, I can change the behavior if you think it should be.

2024-11-12 00:10 UTC, cgillum commented on src/DurableTask.Core/TaskOrchestrationDispatcher.cs
> +            OrchestrationRuntimeState originalOrchestrationRuntimeState = runtimeState.Clone();
I think we're on the same page. Since it doesn't affect the existing behavior (buggy or not), I have no objection to this.

2024-11-12 00:19 UTC, cgillum commented on src/DurableTask.Core/OrchestrationRuntimeState.cs
> +            return new OrchestrationRuntimeState(this.Events)
I don't have a strong opinion. Here's what I think the code would need to be to do a proper deep clone.

```csharp
var cloned = new OrchestrationRuntimeState(this.PastEvents)
{
    CompressedSize = this.CompressedSize,
    Size = this.Size,
    Status = this.Status,
};

foreach (HistoryEvent e in this.NewEvents)
{
    cloned.AddEvent(e);
}

return cloned;
```

2026-06-05 04:14 UTC, closed without merging