Initial implementation of out-of-proc support
Azure/durabletask pull request #656
Opened 2021-12-18 00:04 UTC by cgillum

This PR introduces changes to the DT.Core middleware implementation to enable injecting a custom orchestration processor. The intent is to leverage this for out-of-process execution of orchestrations in Durable Functions and elsewhere.

Part of the change requires a stronger decoupling of the orchestration executor from the dispatcher layer. In particular, two important changes were made:

- Removed usage of the `IsPlayed` property. This value was set in the executor, which is not a change that could be persisted across process boundaries. For that reason, I've decoupled event history into PastEvents and NewEvents as a way to distinguished "played" and "not-yet-played" history events.
- Similarly, custom status is now being saved in the dispatcher layer instead of in the executor layer.

In order to implement .NET-based out-of-process handlers, several internal types were made public.

2022-01-04 23:06 UTC, cgillum reviewed
Added some inline comments to help explain why certain changes were made.

2022-01-04 23:06 UTC, cgillum commented on src/DurableTask.Core/TaskOrchestrationExecutor.cs
> +                    ProcessEvents(newEvents);
The main reason I made the change to distinguish "past" events from "new" events is because I needed a way to preserve the semantic of `HistoryEvent.IsPlayed` for out-of-proc to work (since any changes we make to history events here aren't visible in the "host" process). I could've potentially solved this by just blindly setting all history events to `IsPlayed = true` in TaskOrchestrationDispatcher, but it felt like a strange thing to do. When thinking through this problem, it seemed to me that we didn't need the `IsPlayed` property at all. It's only used to assign the `TaskOrchestrationContext.IsReplaying` property, and this property can already be assigned in a deterministic way without needing to save any IsPlayed data into the storage layer. For these reasons, I decided to just deprecate the IsPlayed property in history and updated this code to simply distinguish past events from new events.

2022-01-04 23:06 UTC, cgillum commented on src/DurableTask.Core/TaskOrchestrationExecutor.cs
> -                this.orchestrationRuntimeState.Status = this.taskOrchestration.GetStatus();
Similar to `IsPlayed`, assigning the `Status` property of the local runtime state object is useless if this code is running out-of-process. For that reason, I instead moved the custom status saving into the `OrchestratorExecutionResult`, which allows custom status to be correctly saved whether we're in-proc or out-of-proc.

2022-01-04 23:06 UTC, cgillum commented on test/DurableTask.AzureStorage.Tests/AzureStorageScenarioTests.cs
> +        public async Task GetInstanceIdsByPrefix()
I created this test a long time ago as part of an unrelated investigation. I decided to include it as part of this PR for convenience. It's not actually related to any of the other changes in this PR.

2022-01-04 23:06 UTC, cgillum commented on test/DurableTask.AzureStorage.Tests/AzureStorageScenarioTests.cs
> +                var status = await client.WaitForCompletionAsync(TimeSpan.FromSeconds(15));
This test was being flakey in the CI because sometimes the orchestration was taking more than 10 seconds to complete. Increasing the timeout made it more reliable.

2022-01-04 23:06 UTC, cgillum commented on test/DurableTask.Core.Tests/DurableTask.Core.Tests.csproj
> +    <TargetFrameworks>netcoreapp3.1;net461</TargetFrameworks>
This fixes all the warnings about .NET Core 2.1 being a deprecated framework. It's not critical for this PR, however.

2022-01-04 23:06 UTC, cgillum commented on tools/DurableTask.props
> +    <LangVersion>9.0</LangVersion>
All DTFx projects use C# 9.0 by default now. This was necessary to get certain features working correctly with nullable reference types.

2022-01-05 23:43 UTC, davidmrdavid reviewed
Exciting changes! Thanks for this PR. I found that, after reading the new tests, the changes in this PR became a lot clearer to me.

I left a few questions, and I'm also a bit concerned about the `isPlayed` change; I understand that failing to update it would break the existing JS/Python implementations.

2022-01-05 23:43 UTC, davidmrdavid commented on src/DurableTask.Core/TaskOrchestrationExecutor.cs
> +    public class TaskOrchestrationExecutor
I'll make sure we're lucky then ;)

2022-01-05 23:43 UTC, davidmrdavid commented on src/DurableTask.Core/TaskOrchestrationExecutor.cs
> +        /// Initializes a new instances of the <see cref="TaskOrchestrationExecutor"/> class.
nit: minor typo

```suggestion
        /// Initializes a new instance of the <see cref="TaskOrchestrationExecutor"/> class.
```

2022-01-05 23:43 UTC, davidmrdavid commented on src/DurableTask.Core/TaskOrchestrationExecutor.cs
> +                    ProcessEvents(newEvents);
In the current Python/JS OOProc model, the `IsPlayed` History property is used to assign the orchestration context's `IsReplaying` flag. I suspect this change would caused a regression there, or won't it?

2022-01-05 23:43 UTC, davidmrdavid commented on src/DurableTask.Core/TaskActivityDispatcher.cs
> +                        }
To me, it makes sense to permanently error-out from instances with this kind of error. Otherwise, I worry about how this may clutter the History and/or lead to some inconsistent state

2022-01-05 23:43 UTC, davidmrdavid commented on src/DurableTask.Core/TaskActivityDispatcher.cs
> +                        var context = new TaskContext(taskMessage.OrchestrationInstance);
Hasn't this `TODO` already been fulfilled with the line immediately below?

2022-01-05 23:43 UTC, davidmrdavid commented on src/DurableTask.Core/History/HistoryEvent.cs
> +        [Obsolete("The IsPlayed property is no longer being set")]
I believe this would affect replay in JS/Python OOProc, because those use the History's `IsPlayed` field to set the orchestration context's `isReplaying` flag.

Btw, I also note this in a later comment.

2022-01-05 23:43 UTC, davidmrdavid commented on src/DurableTask.Core/TaskActivityDispatcher.cs
> +
Unfortunately I don't fully follow the significance of this change. I could use some context.

What are examples of activities supported in the middleware layer, and why wouldn't they be registered as `TaskActivity` classes?

2022-01-06 01:00 UTC, cgillum reviewed
Thanks @davidmrdavid for the review comments? Let me revisit IsPlayed - I think you're probably right that I'm breaking existing DF OOProc scenarios.

See my replies to your other comments below.

2022-01-06 02:04 UTC, cgillum commented
@davidmrdavid I reverted the changes specifically related to `HistoryEvent.IsPlayed` and confirmed that DF JS is now getting the correct values for `context.df.isReplaying`. Thanks for promptly pointing this out. Other PR feedback should also be addressed.

2022-01-07 00:48 UTC, sebastianburckhardt requested changes
Looks good to me in general other than some minor things I commented on.

My confidence about fully understanding the ramifications of the suggested changes is a bit low though.

There is a lot of complexity in the DF shims today, in particular for entities. Many of the things that are changed in this PR were the reason for some complicated workarounds (e.g. the precise way in which middleware gets called, exceptions are handled or converted, and how timeoutes are handled, azure/azure-functions-durable-extension#1917, quite  a nightmare). Those complicated brittle workarounds are at a high risk to break with this PR so I think we need to have a careful look at  them before committing this PR to the main branch. 

In the long run we should be able to simplify things everywhere as we rework the layers but we may break a lot of things in the process unless we coordinate the changes (and the testing) across all the repos. Perhaps we need to have a coordinated "alternate" branch on all the repos?

I also want to test whether this works with Netherite.

2022-01-07 00:48 UTC, sebastianburckhardt commented on src/DurableTask.Core/TaskOrchestrationDispatcher.cs
> +                            workItem.Cursor = null;
Although it is not currently in use, it is conceivable we still want to bring back the "slow continue-as-new" path again at some point.

2022-01-07 22:17 UTC, davidmrdavid commented on src/DurableTask.Core/TaskActivityDispatcher.cs
> +                if (scheduledEvent.Name == null)
My understanding is that a `string?` type is either a `string` or `null`. So I had assumed that changing the type to `string` would force the type-checker to ensure no code-paths allow for a `TaskScheduledEvent.Name` to be `null`. 

Am I misunderstanding something?

2022-01-07 22:29 UTC, davidmrdavid commented on src/DurableTask.Core/TaskActivityDispatcher.cs
> +
Thanks for the clarification. I understand and agree with your comments on the downsides of the current design.

However, I'm personally still confused about this comment: _"With this change, we defer the exception throwing to after all **middleware** has had a chance to run so that we can support activities implemented in the **middleware** layer and not necessarily as registered TaskActivity classes (in theory, **middleware** could also inject a TaskActivity object now, but that's not a scenario we particularly care about)."_

I think the confusing bit here is that that I don't have a firm grasp of what the middleware was doing before, and what it's doing now. I do have _some_ working understanding, but it's finicky. I'd love to have a chat about this, as I'm unsure I'll get much clarity on this via async comments alone :)

2022-01-07 22:31 UTC, cgillum reviewed
I'll add another iteration with my proposed changes, but here's my feedback responses for now.

2022-01-07 22:31 UTC, cgillum commented on src/DurableTask.Core/OrchestrationRuntimeState.cs
> +                return ExecutionStartedEvent?.Timestamp ?? default;
I think what I'll do is replace the assert statements with exceptions so that we have a proper contract that has stronger null guarantees.

2022-01-07 22:32 UTC, davidmrdavid commented on src/DurableTask.Core/TaskActivityDispatcher.cs
> +                        }
Good to know this won't clutter the history. I don't have strong feelings about this behavior, but the repeated exceptions (forever or until expiration) still seems like undesirable behavior to me. Just giving my 2 cents, I realize this behavior is outside the scope of this PR :)

2022-01-07 22:35 UTC, davidmrdavid commented on src/DurableTask.Core/TaskOrchestrationExecutor.cs
> +                    ProcessEvents(newEvents);
Yeah I'm also fully on board with removing IsPlayed and other logically unecessary fields in the near future. If / when we finalize the design for the OOProc Task layer, it would be good to revisit these things.

2022-01-07 22:40 UTC, cgillum commented on src/DurableTask.Core/TaskActivityDispatcher.cs
> +                if (scheduledEvent.Name == null)
Let me answer your original question differently: we can't change from `string?` to `string` because there are existing public constructors that allow you to create a `TaskScheduledEvent` without initializing the `Name` property. Removing those constructors would be a breaking change, which I want to avoid. In addition to this, the C# compiler is unable to make any guarantees about nullability when objects of a given type are created/manipulated via reflection. The Newtonsoft.Json serializer is an example of a component that can create an initialize types using private reflection. For that reason, in order to be defensive against bad JSON payloads, I'm intentionally using `string?` instead of `string` even though theoretically I might not need to (though in reality, I actually do need `string?` due to my earlier point).

2022-01-07 22:41 UTC, cgillum commented on src/DurableTask.Core/TaskActivityDispatcher.cs
> +
Hopefully this will be more clear when I publish my Durable Functions extension PR.

2022-01-07 23:30 UTC, cgillum commented on src/DurableTask.Core/OrchestrationRuntimeState.cs
> +        public IList<HistoryEvent> PastEvents { get; }
I take it back - it looks like there are several places in the code where `NewEvents` gets cleared but all the existing events are supposed to be kept in memory. `Events` is therefore _not always_ a combination of these two lists and some redundancy is required. It would probably take a bunch of refactoring to remove this redundancy, but I don't want to risk it as part of this PR.

2022-01-10 17:55 UTC, cgillum commented on src/DurableTask.Core/OrchestrationRuntimeState.cs
> +            PastEvents = new List<HistoryEvent>(events?.Count ?? 32);
I changed the expressions to remove the hardcoded numbers.

2022-01-10 22:28 UTC, davidmrdavid approved these changes
LGTM, especially now that `isPlayed` is preserved. Left a tiny nit.
I'd love to get @sebastianburckhardt's approval before merge as well.

2022-01-10 22:28 UTC, davidmrdavid commented on src/DurableTask.Core/OrchestrationRuntimeState.cs
> +        // This gets called by json.net for deserialization, we can't throw if there is no ExecutionStartedEvent
nit: I'd appreciate a tiny edit to this comment where we specify that, even though we're not throwing in here, we do throw an exception later in the code if `ExecutionStartedEvent` is null.

2022-01-10 22:33 UTC, cgillum commented on src/DurableTask.Core/OrchestrationRuntimeState.cs
> +        // This gets called by json.net for deserialization, we can't throw if there is no ExecutionStartedEvent
I think I'll just get rid of this comment. I'm not even sure it's accurate (the original comment predates me).

2022-01-11 15:23 UTC, sebastianburckhardt approved these changes
The changes look good to me.

I also did a quick test with Netherite and it seems to work without any issues.

2022-01-11 18:16 UTC, merged