Add exception information to traces
Azure/durabletask pull request #694
Opened 2022-03-16 23:53 UTC by bachuv

This PR adds exception information to traces when an orchestration or activity throws an exception. Two tags are added to the trace Activity: `otel.status_code` and `otel.status_description`. These tags are how the Activity status is set.

```
activity?.SetTag("otel.status_code", "ERROR");
activity?.SetTag("otel.status_description", "description");
```

This is the approach we are using to set the Activity's status. This is what is listed in the .NET distributed tracing docs:

>OpenTelemetry allows each Activity to report a [Status](https://github.com/open-telemetry/opentelemetry->specification/blob/main/specification/trace/api.md#set-status) that represents the pass/fail result of the work. .NET does not currently have a strongly typed API for this purpose but there is an established convention using Tags

Reference:
[Add distributed tracing instrumentation - .NET | Microsoft Docs](https://docs.microsoft.com/en-us/dotnet/core/diagnostics/distributed-tracing-instrumentation-walkthroughs#optional-add-status)

This PR is currently a draft PR until the `otel.status_description` tag is finalized with the information we want to add. We could also add additional tags to split up the information.

Images:
<img width="960" alt="image" src="https://user-images.githubusercontent.com/15795068/158708917-651dee0c-c5bc-4b7e-bf90-51b2698c995d.png">

<img width="957" alt="image" src="https://user-images.githubusercontent.com/15795068/158708998-2b723a99-8d0d-4a54-8a88-37a94e7c08bb.png">

<img width="958" alt="image" src="https://user-images.githubusercontent.com/15795068/158709165-caa3298e-ff57-48e7-a8af-ca172ee7df43.png">

2022-03-17 00:24 UTC, cgillum reviewed
I love this! I suggest we have a more specific value for otel.status_description.

2022-03-17 00:24 UTC, cgillum commented on src/DurableTask.Core/TaskActivityDispatcher.cs
> +                        traceActivity?.SetTag("otel.status_description", e.Message + "\n" + details);
I suggest we have a more condensed error description:
```suggestion
                        traceActivity?.SetTag("otel.status_description", $"{e.GetType().FullName}: {e.Message}");
```

In the above example, this would result in "__System.InvalidOperationException: This is an invalid operation__", which I think is enough information for distributed tracing. The full exception information (call-stack, etc.) should be in the existing logs anyways. I don't want to use `details` because that's an internal, serialized representation of the exception that we should avoid logging.

2022-03-17 00:26 UTC, cgillum commented
Tagging @jviau for comments.

2022-03-17 19:02 UTC, bachuv commented on src/DurableTask.Core/TaskActivityDispatcher.cs
> +                        traceActivity?.SetTag("otel.status_description", e.Message + "\n" + details);
That makes sense. I tried `e.GetType().FullName` and it resolves to `DurableTask.Core.Exceptions.TaskFailureException`. I then tried `e.InnerException.GetType().FullName` and it resolved to `System.InvalidOperationException`. I'll replace the existing `otel.status_description` value with `$"{e.InnerException.GetType().FullName}: {e.Message}`. 

I'll also make the same change in the orchestration exception code section to remove `details`.

<img width="959" alt="image" src="https://user-images.githubusercontent.com/15795068/158876633-9bdb71e3-da53-4a43-8b36-ca52c6a57aa9.png">

<img width="958" alt="image" src="https://user-images.githubusercontent.com/15795068/158876703-e7d02d23-cff4-48fb-972a-01365cfaa14e.png">

2022-03-17 19:45 UTC, cgillum commented on src/DurableTask.Core/TaskActivityDispatcher.cs
> +                        traceActivity?.SetTag("otel.status_description", $"{e.InnerException?.GetType().FullName}: {e.Message}");
Since this catch block catches anything that derives from `Exception`, I don't think it makes sense to use the inner exception here since we can't make any assumptions about whether there will be an inner exception. Instead, just do this:
```suggestion
                        traceActivity?.SetTag("otel.status_description", $"{e.GetType().FullName}: {e.Message}");
```

2022-03-17 20:51 UTC, jviau commented
FYI, otel exception status is in flux.

1. OTel has an extension method themselves: https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry.Api/Trace/ActivityExtensions.cs#L44 (if you want to take a dependency on OpenTelemetry.Api, which you probably don't in the core package. Would need some architecture to introduce `DurableTask.OpenTelemetry` package which would perform otel-specific enrichment of DTFx Activities).
1. `System.Diagnostics.DiagnosticSource` >= 6.0.0 has added an `Activity.SetStatus()` method, which does basically exactly what you want. Problem is, OTel does not yet support that: https://github.com/open-telemetry/opentelemetry-dotnet/issues/2569

Ultimately, I think you may want to use the built in `Activity.SetStatus()` from 6.0.0 package?

2022-03-17 23:21 UTC, cijothomas commented
> Activity.SetStatus() from 6.0.0 package

^ Please use this. The OpenTelemetry SDK/Exporters will support this in coming stable release.

2022-03-23 17:45 UTC, bachuv commented
I tried updating `System.Diagnostics.DiagnosticSource` to 6.0.0, but I'm seeing an issue with `System.Runtime.CompilerServices.Unsafe` in some DTFx projects.

> System.Runtime.CompilerServices.Unsafe doesn't support netcoreapp2.1. Consider updating your TargetFramework to netcoreapp3.1 or later

`System.Diagnostics.DiagnosticSource` v6.0.0 depends on `System.Runtime.CompilerServices.Unsafe` v6.0.0, but `System.Runtime.CompilerServices.Unsafe` v6.0.0 isn't compatible with `netcoreapp2.1` as the TargetFramework.

I don't think updating the TargetFramework would be in the scope of this feature right now. @cgillum Do you have any thoughts about this?

2022-03-23 18:01 UTC, cgillum commented
I don't think we can upgrade to System.Diagnostics.DiagnosticSource unless we can verify that the Functions runtime (which we have to support) also uses this version. Last I checked, they use 5.0.0.

Upgrading from `netcoreapp2.1` to something newer is something we should do at some point since this framework version is already deprecated. I don't mind doing it now, but I'd say let's do it only if we absolutely have to.

2022-03-23 18:12 UTC, jviau commented
Unfortunate you cannot update to 6.0.0 yet. Do you have a plan for that? Or can we open an issue to track that work and whatever its dependencies are?

Also, there are some additional exception tracking details we can do here:
https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/exceptions.md
https://cs.github.com/open-telemetry/opentelemetry-dotnet/blob/bdcf942825915666dfe87618282d72f061f7567e/src/OpenTelemetry.Api/Trace/ActivityExtensions.cs#L32

`Activity.RecordException` extension method, or at least duplicate that behavior if you don't want to take a dependency on `OpenTelemetry.Api`.  This is optional of course, but it would be nice so exporters can record the exception type and other details.

2022-03-23 18:26 UTC, cijothomas commented on src/DurableTask.Core/TaskActivityDispatcher.cs
> +                        traceActivity?.SetTag("otel.status_description", $"{e.GetType().FullName}: {e.Message}");
https://github.com/open-telemetry/opentelemetry-specification/pull/2368/files

2022-03-23 18:28 UTC, cijothomas commented
> Unfortunate you cannot update to 6.0.0 yet. Do you have a plan for that? Or can we open an issue to track that work and whatever its dependencies are?
> 
> Also, there are some additional exception tracking details we can do here: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/exceptions.md https://cs.github.com/open-telemetry/opentelemetry-dotnet/blob/bdcf942825915666dfe87618282d72f061f7567e/src/OpenTelemetry.Api/Trace/ActivityExtensions.cs#L32
> 
> `Activity.RecordException` extension method, or at least duplicate that behavior if you don't want to take a dependency on `OpenTelemetry.Api`. This is optional of course, but it would be nice so exporters can record the exception type and other details.

https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/exceptions.md -- The spec which suggests storing Exception as SpanEvent is *experimental*, so please be aware of this. (since not stable, this could change in the future)

2022-03-29 00:42 UTC, bachuv commented on src/DurableTask.Core/TaskActivityDispatcher.cs
> +                        traceActivity?.SetTag("otel.status_description", $"{e.GetType().FullName}: {e.Message}");
@cijothomas Thanks for pointing this out! Looks like maybe we should use a different tag key to emit information about the exception instead of `otel.status_description` then.

2022-03-30 21:14 UTC, bachuv commented on src/DurableTask.Core/TaskActivityDispatcher.cs
> +                        traceActivity?.SetTag("otel.status_description", $"{e.GetType().FullName}: {e.Message}");
I updated the tag key to be "exception_description".

2022-03-30 21:18 UTC, jviau commented on src/DurableTask.Core/TaskActivityDispatcher.cs
> +                        traceActivity?.SetTag("otel.status_description", $"{e.GetType().FullName}: {e.Message}");
@bachuv would it be better to split these into two tags? `exception.type` and `exception.message`?

2022-03-31 00:35 UTC, cgillum requested changes
One blocking issue, which is that I think the mechanism for capturing orchestration failures won't work for Durable Functions as-is.

2022-03-31 01:44 UTC, cijothomas commented on src/DurableTask.Core/TaskOrchestration.cs
> +                DistributedTraceActivity.Current?.SetTag("exception.message", e.Message);
The OTel convention is to use ActivityEvent for exception. See https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/exceptions.md. (entire Otel convention is experimental, so you may/may not want to take a dependency on it.). If not taking a dependency on it, but doing own conventions, without someone translating this, no exporter will be able to understand this.
For example: an AzureMonitor exporter will be looking for exceptions in a particular place. If it is provided elsewhere, it won't treat it as exception, but rather as any other random tag.

2022-03-31 16:58 UTC, bachuv commented on src/DurableTask.Core/TaskOrchestration.cs
> +                DistributedTraceActivity.Current?.SetTag("exception.message", e.Message);
I tried looking through `OnProcessWorkItemAsync()`, but I don't see a place where we would have access to the exception that was thrown. My original thought was to check if the orchestration status was `Failed` and then add this information. Do you have any recommendations on where else we would have access to the exception? Is this something that could be handled in the Durable Functions extension?

2022-03-31 17:11 UTC, jviau commented on src/DurableTask.Core/TaskOrchestration.cs
> +                DistributedTraceActivity.Current?.SetTag("exception.message", e.Message);
I was looking through the AzureMonitor exporter and couldn't find any trace exception logic. Maybe I am just missing it?

I don't have a strong opinion on _how_ DTFx tracks exception info here. So long as it does it in some way or another and that whatever tag names or event names used are at least kind of consistent with how all other property naming is done. Also that type and message are separate tags.

But as for event vs tags, that I am unsure. Whichever DTFx goes with may have be ready to change it. But with that said _maybe_ it is a lower chance it has to change if it takes on the current otel exception experimental spec? That _might_ be become stable and unchanged. But if it does change, oh well - DTFx can change as well.

2022-03-31 17:11 UTC, cijothomas commented on src/DurableTask.Core/TaskOrchestration.cs
> +                DistributedTraceActivity.Current?.SetTag("exception.message", e.Message);
> (AzureMonitor added support for it recently only I think, probably not yet released.).

^ This is incorrect. I don't it adding support yet.

2022-03-31 17:48 UTC, cgillum commented on src/DurableTask.Core/TaskOrchestration.cs
> +                DistributedTraceActivity.Current?.SetTag("exception.message", e.Message);
Oh yeah, you're right - it looks like we don't have a clean way of getting any information about the exception except for this one spot. :(

In a recent [PR that I merged](https://github.com/Azure/durabletask/pull/681), we do expose the exception type and exception message as part of a "FailureDetails" object which I think should be available in OnProcessWorkItemAsync. If you sync with the latest changes from `main`, you should be able to see it. However, the failure details are only populated when a certain error propagation mode is enabled, so sometimes this value will be null. Unfortunately, this new code path will only be enabled for .NET Isolated and Java, or for DTFx users that enable this flag.

My recommendation is that we do a "best effort" here and check for the `Failed` status like you suggested and set the `otel.status_code` status like you are now. If we can find non-null FailureDetails, then we can add the other tags for the exception type and message. This compromise means that some users won't see the exception type and message, but at least we'll know that everyone can see the status code.

2022-03-31 18:18 UTC, jviau commented on src/DurableTask.Core/TaskOrchestration.cs
> +                DistributedTraceActivity.Current?.SetTag("exception.message", e.Message);
To me I see great value in seeing that exception - at least the type and message - right in the distributed trace explorer. So that only works I think if you selected trace exporter knows about the logs (so would ZipKin know about that logged exception in this case?). This does work great when using AzureMonitor / ApplicationInsights. It shows logged exceptions underneath the parent span in the trace explorer.

But still, having the exception logged and not in the activity is better than nothing for sure.

2022-03-31 19:12 UTC, cijothomas commented
1. Follow the OTel semantic conventions as is. Mark this feature as experimental/similar, and document that this is based on Otel conventions, and could change in the future. The owners of this repo, should need update the code whenever semantic conventions change. Once they achieve stable status, there'll be only additive changes. If there is breaking change, then it'll be covered by schema_url + transitions.
2. Follow own conventions. Must at least document the conventions. 

Approach 1 ensures that most tools in OpenTelemetry ecosystem understands this nicely. 
Approach 2 means someone has to do a translation from own conventions to the one understood by the OpenTelemetry based tools. This repo owners could maintain a Instrumentation Library which can do this translation (and keep it updated all the time). Or leave it up to users to do the mapping somewhere.

2022-06-14 18:38 UTC, bachuv commented on src/DurableTask.Core/TaskOrchestration.cs
> +                DistributedTraceActivity.Current?.SetTag("exception.message", e.Message);
I pulled the latest from `main`, added the check for `Failed` status, and incorporated `FailureDetails`. How would customers configure `ErrorPropagationMode.UseFailureDetails` if they are using Durable Functions?

2022-06-14 19:37 UTC, cgillum commented on src/DurableTask.Core/TaskOrchestration.cs
> +                DistributedTraceActivity.Current?.SetTag("exception.message", e.Message);
We don't expose this as a configuration option today. However, it's enabled by default for Java and .NET Isolated.

2022-08-24 20:49 UTC, cgillum commented
It looks like this PR is suddenly showing changes from other PRs that have already been merged, so I'm having trouble seeing what I should actually be reviewing. @bachuv are you able to update the PR to show only your changes?

2023-02-07 21:56 UTC, bachuv commented
Closing in favor of #853

2023-02-07 21:56 UTC, closed without merging