Include LeaseType in lease-stealing flow
Azure/durabletask pull request #699
Opened 2022-03-31 10:16 UTC by saguiitay

Include LeaseType in lease-stealing flow. This should make it easier to troubleshoot lease-stealing flows.

2022-03-31 10:16 UTC, saguiitay commented
@cgillum

2022-03-31 16:53 UTC, cgillum commented
@amdeel can you take a look?

2022-04-01 16:53 UTC, cgillum requested changes

2022-04-01 16:53 UTC, cgillum commented on src/DurableTask.AzureStorage/AnalyticsEventSource.cs
> +            string LeaseType,
Since we're adding a new field, we need to update the `Version` attribute value above to `3`.

2022-04-01 16:53 UTC, cgillum commented on src/DurableTask.AzureStorage/AnalyticsEventSource.cs
> +            string LeaseType,
Since we're adding a new field, we need to update the `Version` attribute value above to `3`.

2022-04-07 17:20 UTC, cgillum commented
/azp run

2022-04-07 19:43 UTC, cgillum approved these changes
LGTM!

2022-04-07 19:43 UTC, merged