Purge instance history support
Azure/durabletask pull request #704
Opened 2022-04-13 21:39 UTC by shreyas-gopalakrishna

- Adds purge instance history support
- Deprecates src/DurableTask.AzureStorage/PurgeHistoryResult.cs

Reference: https://github.com/microsoft/durabletask-java/issues/10

2022-04-13 22:11 UTC, shreyas-gopalakrishna commented on src/DurableTask.AzureStorage/AzureStorageOrchestrationService.cs
> +        public Task<Core.PurgeHistoryResult> PurgeInstanceHistoryAsync(DateTime createdTimeFrom, DateTime? createdTimeTo, IEnumerable<OrchestrationStatus> runtimeStatus)
Should we retain this to AzureStorage/PurgeHistoryResult and convert it to Core/PurgeHistoryResult in the `PurgeInstanceStateAsync` method?

2022-04-13 22:41 UTC, cgillum requested changes
Thanks for this PR! I think we need to make this change in a way that's non-breaking. See my comments below.

2022-04-13 22:41 UTC, cgillum commented on src/DurableTask.Core/IOrchestrationServicePurgeClient.cs
> +        /// <returns><see cref="PurgeHistoryResult"/> object containing number of storage requests sent, along with instances and rows deleted/purged.</returns>
This description assumes the Azure Storage backend, which isn't always going to be the one used. Let's simplify it.
```suggestion
        /// <returns><see cref="PurgeHistoryResult"/> object containing more information about the purged instance.</returns>
```

2022-04-13 22:41 UTC, cgillum commented on src/DurableTask.Core/PurgeHistoryResult.cs
> +        public int InstancesDeleted { get; }
For DurableTask.Core, this should be the only property we use. The other two may not always be relevant. We can add more properties later that may be universally interesting. For example, the number of bytes freed.

2022-04-13 22:41 UTC, cgillum commented on src/DurableTask.Core/IOrchestrationServicePurgeClient.cs
> +        Task<PurgeHistoryResult> PurgeInstanceStateAsync(DateTime createdTimeFrom, DateTime? createdTimeTo, IEnumerable<OrchestrationStatus> runtimeStatus);
Rather than having discrete parameters, I think we should have a single object with multiple properties as the one parameter. That way we can more easily add new criteria without making a breaking interface change.

2022-04-13 22:41 UTC, cgillum commented on src/DurableTask.AzureStorage/AzureStorageOrchestrationService.cs
> +        public Task<Core.PurgeHistoryResult> PurgeInstanceHistoryAsync(DateTime createdTimeFrom, DateTime? createdTimeTo, IEnumerable<OrchestrationStatus> runtimeStatus)
We need to retain the existing methods. Otherwise, we're introducing a breaking change. which we need to avoid for now. This best way to make this work is to have `AzureStorageOrchestrationService` implement the `IOrchestrationServicePurgeClient` interface explicitly. The syntax will look something like this:

```csharp
Task<Core.PurgeHistoryResult> IOrchestrationServicePurgeClient.PurgeInstanceStateAsync(string instanceId)
{
    return this.PurgeInstanceHistoryAsync(instanceId);
}

async Task<Core.PurgeHistoryResult> IOrchestrationServicePurgeClient.PurgeInstanceStateAsync(DateTime createdTimeFrom, DateTime? createdTimeTo, IEnumerable<OrchestrationStatus> runtimeStatus)
{
    PurgeHistoryResult storagePurgeResult = await this.PurgeInstanceHistoryAsync(createdTimeFrom, createdTimeTo, runtimeStatus);
    return storagePurgeResult.ToCorePurgeResult(); // <-- some new method that converts between the two types
}
```

2022-04-13 22:41 UTC, cgillum commented on src/DurableTask.AzureStorage/PurgeHistoryResult.cs
> +    [Obsolete("Not used any more. Will use DurableTask.Core.PurgeHistoryResult going forward.", true)]
Let's not mark this as obsolete yet, since introducing warnings could be a breaking change for some. Also, the new Core.PurgeHistoryResult isn't a perfect replacement, so we need to think through the deprecation strategy a bit more (but this can be done later).

2022-04-14 21:13 UTC, cgillum commented on src/DurableTask.AzureStorage/AzureStorageOrchestrationService.cs
> +        /// <returns><see cref="PurgeResult"/> object containing more information about the purged instance.</returns>
Rather than duplicating the description of this method, just add `/// <inheritdoc />`. That will cause it to refer to the documentation comments on the interface declaration.

2022-04-14 21:13 UTC, cgillum commented on src/DurableTask.Core/IOrchestrationServicePurgeClient.cs
> +        /// <param name="purgeInstanceCondition"><see cref="PurgeInstanceCondition"/>Conditions that should match to purge orchestration history.</param>
The formatting of this comment doesn't look right. The description is also a little ambiguous. Here's a suggestion:

```suggestion
        /// <param name="purgeInstanceCondition">A <see cref="PurgeInstanceCondition"/> object that determines which orchestration instance to purge.</param>
```

2022-04-14 21:13 UTC, cgillum commented on src/DurableTask.Core/PurgeInstanceCondition.cs
> +    public class PurgeInstanceCondition
I gave similar feedback in Kaibo's PR, but let's not use the "Condition" suffix. It doesn't sound natural. Something like `PurgeInstanceCriteria` or `PurgeInstanceFilter` would be better.

2022-04-15 20:18 UTC, cgillum approved these changes

2022-04-15 21:20 UTC, merged