Finish first draft suspend-resume feature
Azure/durabletask pull request #764
Opened 2022-07-13 21:31 UTC by Julio-Arroyo

2022-07-14 00:59 UTC, cgillum reviewed
Initial batch of comments. I'll try to add more over the next couple of days.

2022-07-14 14:52 UTC, aueloka commented
Just curious about the design for this feature. How would sub orchestrations be handled? Would a "suspend" on the parent fan out "suspend" events to all running sub orchestrations? Or would any running sub orchestration still proceed while the parent is suspended?

2022-07-14 14:58 UTC, cgillum commented
@aueloka the current design only suspends the target orchestration. Sub-orchestrations would continue running.

2022-07-14 16:31 UTC, davidmrdavid commented on src/DurableTask.AzureStorage/OrchestrationSessionManager.cs
> +            {
Let's remove this whitespace :)

2022-07-14 16:34 UTC, davidmrdavid commented on src/DurableTask.AzureStorage/Tracking/AzureTableTrackingStore.cs
> +                            instancePropertyName: OutputProperty,
I also noticed we're using `executionTerminatedEvent.Input` in this block, which seems like an event for terminate instead of suspend.

2022-07-14 16:37 UTC, davidmrdavid commented on src/DurableTask.Core/SuspendedOrchestrationMessageInfo.cs
> +        public TaskOrchestration taskOrchestration;
Can you clarify this comment some more? What was the alternative that did not work?

2022-07-14 16:38 UTC, davidmrdavid commented on src/DurableTask.Core/TaskOrchestrationContext.cs
> +        public bool executionSuspended;
nit: maybe rename to `isSuspended`?

2022-07-14 16:39 UTC, davidmrdavid commented on src/DurableTask.Core/TaskOrchestrationExecutor.cs
> -
can we add this whitespace back?

2022-07-14 16:40 UTC, davidmrdavid commented on src/DurableTask.Core/TaskOrchestrationContext.cs
> +                        throw new NotImplementedException("Found unkown event when resuming orchestration.");
typo: unkown -> unknown

2022-07-14 16:43 UTC, davidmrdavid commented on src/DurableTask.Core/TaskOrchestrationContext.cs
> +        }
Hmm, I would like us to consider this logic some more. It seems that this assumes that orchestrators only receive a "suspend" resume once before getting resumed, but what happens if they receive multiple suspend-requests before receiving any resume-requests?

From the current logic, it would seem each subsequent resume would clear the buffer of messages, or am I reading this wrong?

2022-07-14 16:48 UTC, davidmrdavid commented on src/DurableTask.Core/TaskOrchestrationContext.cs
> +                    case EventType.TaskCompleted:
I worry about this method duplicating some of the logic we already have in `ProcessEvent`. Is it possible at all to re-use that code directly?

2022-07-14 16:49 UTC, davidmrdavid reviewed
Also left a first batch of comments!

2022-07-15 20:34 UTC, Julio-Arroyo commented on src/DurableTask.AzureServiceFabric/FabricOrchestrationServiceClient.cs
> +        public Task ForceResumeTaskOrchestrationAsync(string instanceId, string reason)
Done.

2022-07-15 20:41 UTC, Julio-Arroyo commented on src/DurableTask.AzureStorage/OrchestrationSessionManager.cs
> +                }
You are right, this is some logic I forgot to remove from the prototype implementation.

2022-07-18 18:18 UTC, Julio-Arroyo commented on src/DurableTask.Core/SuspendedOrchestrationMessageInfo.cs
> +        public TaskOrchestration taskOrchestration;
When implementing this, I had to consider two things: I needed access to the `isSuspended` flag (which is in `TaskOrchestrationContext.cs`) and needed the `taskOrchestrationContext` (which is in `TaskOrchestrationExecutor`) to make the `RaiseEvent()` call. Since I decided to use handlers in `TaskOrchestrationExecutor.cs` for `ExecutionResumedEvent` and `ExecutionSuspendedEvent`, then the logic is in `TaskOrchestrationContext.cs`.

Notice that the only `EventType` in `ProcessEvent` that does not make use of a handler is the `EventRaised`. Thus, I encountered the challenge that if I was dealing with `EventRaised` when resuming the orchestration, I could not make the `RaiseEvent()` call as usual.

2022-07-18 18:25 UTC, Julio-Arroyo commented on src/DurableTask.Core/TaskOrchestrationContext.cs
> +        }
I agree that these assumptions are not safe to make. I want to argue, though, that those cases are dealt with.

The suspend (resp. resume) request will go through if and only if the orchestration is in the running (resp. suspended) state. This is implemented in `DurableClient.cs` in the DF extension, in the `SuspendAsync` (resp. `ResumeAsync)` methods.

Let me know @davidmrdavid if that sounds reasonable, if you think that this logic should be enough to deal with the cases you mentioned.

2022-07-18 18:29 UTC, Julio-Arroyo commented on src/DurableTask.Core/TaskOrchestrationContext.cs
> +                    case EventType.TaskCompleted:
Good point. With some refactoring, it may be possible to call `ProcessEvent()` directly? The issue is that all this logic is spread across two classes `TaskOrchestrationContext.cs` and `TaskOrchestrationExecutor.cs`. I left some discussion about this in your comment asking for further clarification on the `SuspendedOrchestrationMessageInfo.cs`.

2022-07-18 23:12 UTC, cgillum reviewed
A few more comments from me, this time focused on the core of the implementation.

2022-07-18 23:12 UTC, cgillum commented on src/DurableTask.Core/TaskOrchestrationContext.cs
> +            suspendedOrchestrationMessages = null;
Consider making this field never null - i.e. initialize it in the constructor and mark it as `readonly`. That may help reduce some of the overall complexity of your change.

2022-07-18 23:12 UTC, cgillum commented on src/DurableTask.Core/OrchestrationRuntimeState.cs
> +                _orchestrationStatus = value;
I don't feel good about this change because it fundamentally changes some of the assumptions we can make about the OrchestrationRuntimeState class. The design of this class, from my perspective, is to derive all properties from the history events. Making this property settable breaks that and will likely introduce new complexity. I suggest instead that you remove the setter and update the orchestration status field at the point in time where you're adding new history events. I think the `SetMarkerEvents` method would be a good place to check for your new history events and update the internal orchestration status accordingly.

2022-07-18 23:12 UTC, cgillum commented on src/DurableTask.Core/OrchestrationRuntimeState.cs
> +            // OrchestrationStatus = orchStatus;
Can this be removed?

2022-07-18 23:12 UTC, cgillum commented on src/DurableTask.Core/OrchestrationRuntimeState.cs
> +        public OrchestrationStatus _orchestrationStatus;
This is clearly an internal field, so you should remove `public`.  I also recommend removing the `_` prefix since we don't use that convention elsewhere in this code.

2022-07-19 16:16 UTC, davidmrdavid commented on src/DurableTask.Core/TaskOrchestrationContext.cs
> +        }
Just writing down the takeaways of our discussion, @Julio-Arroyo.

So I'm not certain that we can **enforce** the invariant that orchestrations only receive suspend requests when they're running. It could be the case that two clients send suspend requests at the same time, and each of them would think the orchestration is running, but the orchestrator would receive two requests. As a result, I suggest making the code resilient to this possibility :)

2022-07-21 16:36 UTC, davidmrdavid commented on src/DurableTask.AzureServiceFabric/FabricOrchestrationServiceClient.cs
> +            throw new NotImplementedException();
We should make a note to notify the ServiceFabric backend maintainers about this change.

2022-07-21 16:56 UTC, davidmrdavid commented on test/DurableTask.Test.Orchestrations/SimpleOrchestrations.cs
> +        }
Interesting, I was under the impression that `setCustomStatus` was already a DurableTask-level API. From this change, it seems that it's only implemented at the Durable Extension level. _The more you know :)_

2022-07-21 16:57 UTC, davidmrdavid commented on test/DurableTask.Test.Orchestrations/SimpleOrchestrations.cs
> +            }
Do we really need this return statement? Isn't it safe to also just set the customStatus to the empty string?

2022-07-21 17:44 UTC, Julio-Arroyo commented on test/DurableTask.AzureStorage.Tests/AzureStorageScenarioTests.cs
> +        }
@amdeel Added this basic test. We didn't explicitly discuss it before, but this was some core functionality that was giving me issues when testing other things, so I figured I better test for this explicitly.

2022-07-21 17:49 UTC, Julio-Arroyo commented on test/DurableTask.AzureStorage.Tests/AzureStorageScenarioTests.cs
> +                                await Task.Delay(2000);
@amdeel I decided that for this test scenario, I would rather go with the custom status approach (rather than the "bomb", or throwing exception, which you can find commented out). For one, it follows the template of other tests in this file, so I am using patterns already in place. Another reason is that checking the expected observed behavior explicitly might be better than trying to avoid an exception.

2022-07-21 20:22 UTC, davidmrdavid commented on src/DurableTask.Core/History/ExecutionResumedEvent.cs
> +        public string Input { get; set; }
@Julio-Arroyo: just to be sure - if we wanted to name this field `Reason` instead of `Input`, then would it be possible to rename this field and its accessors to make that work? I think the answer is _yes_, and I believe that's what Chris was suggesting here.

2022-07-21 20:24 UTC, davidmrdavid commented on src/DurableTask.Core/OrchestrationRuntimeState.cs
> +                return orchestrationStatus;
Given that we've returned this field into a "getter", do we still need this new `return` statement in it?

2022-07-21 20:32 UTC, davidmrdavid commented on test/DurableTask.Test.Orchestrations/SimpleOrchestrations.cs
> +    public sealed class ChangeStatusOrchestration2 : TaskOrchestration<string, string>
Let's make sure to drop the `2` at the end of this name once we're done reviewing the tests :)

2022-07-21 20:33 UTC, davidmrdavid commented on test/DurableTask.Test.Orchestrations/SimpleOrchestrations.cs
> +            await context.CreateTimer<int>(context.CurrentUtcDateTime, 0);
Interesting, I also didn't expect the "dummy timer" to be required. I'd love @amdeel's confirmation on this one.

2022-07-21 20:36 UTC, davidmrdavid reviewed
Left some comments. Overall, I like the testing strategy with the custom status and I think the tests are fine as-is. 

My main blocker before merging this PR is the code duplication in `HandleExecutionResumedEvent`. I'd love to reach a resolution on that :)

2022-07-21 20:55 UTC, Julio-Arroyo commented on src/DurableTask.Core/TaskOrchestrationContext.cs
> +                    case EventType.TaskCompleted:
Using your ideas, I refactored the signature of `HandleExecutionResumed` method to take a function pointer, so that the same code can be reused to process the events.

2022-07-21 23:25 UTC, amdeel reviewed
Left some initial feedback. I'll get to the testing component later today.

2022-07-21 23:25 UTC, amdeel commented on src/DurableTask.Core/TaskOrchestrationContext.cs
> +                    suspendedOrchestrationMessages.Enqueue(msgInfo);
I don't love this design. I think we could enqueue messages in ProcessEvent instead. This would also make sure we handle all incoming messages when the orchestrator is in the suspended state without missing any, including Timer messages. It also future-proofs the design to handle any new event type we may eventually add.

2022-07-21 23:25 UTC, amdeel commented on src/DurableTask.Core/TaskOrchestrationExecutor.cs
> +                        this.context.AddSuspendedOrchestrationMessage(msgInfo);
See my comment above. We can remove this code duplication.

2022-07-21 23:25 UTC, amdeel commented on src/DurableTask.Core/TaskOrchestrationContext.cs
> +                    case EventType.TaskCompleted:
I agree, you should call ProcessEvent for each of the queue messages instead of adding this method. Reach out if you're struggling with the refactor.

2022-07-22 06:38 UTC, amdeel commented on test/DurableTask.AzureStorage.Tests/AzureStorageScenarioTests.cs
> +        public async Task SuspendResumeCheckStatus()
We want to make sure we cover all the test cases, you can even add comments in code to be clear about what you're testing if you want to, but I think we can consolidate this code and get rid of the code duplication by merging these tests.

2022-07-22 16:33 UTC, davidmrdavid commented on test/DurableTask.AzureStorage.Tests/AzureStorageScenarioTests.cs
> +        public async Task SuspendResumeCheckStatus()
@amdeel: I'm not entirely clear on which tests you're suggesting should get merged :) . Can you please clarify?

2022-07-22 16:34 UTC, davidmrdavid commented on src/DurableTask.Core/TaskOrchestrationContext.cs
> +                    suspendedOrchestrationMessages.Enqueue(msgInfo);
I agree with this, let's see if we can generalize this enqueue'ing to work for all events in `ProcessEvent`. Otherwise, we have code duplication that will be harder to maintain.

2022-07-22 16:48 UTC, davidmrdavid commented on src/DurableTask.Core/SuspendedOrchestrationMessageInfo.cs
> +    class SuspendedOrchestrationMessageInfo
Yep - now that `ProcessEvent` has been refactored to be recursive, I think you can safely remove this class, right?

2022-07-22 18:31 UTC, amdeel commented on test/DurableTask.AzureStorage.Tests/AzureStorageScenarioTests.cs
> +        public async Task SuspendResumeCheckStatus()
Most of the test methods can be merged into one.

2022-07-22 18:35 UTC, Julio-Arroyo commented on src/DurableTask.Core/TaskOrchestrationContext.cs
> +                    suspendedOrchestrationMessages.Enqueue(msgInfo);
I love this suggestion! Based on this, I have made the following changes, which I think make the implementation easier to follow and avoid code duplication:

- In `ProcessEvent` I have added a generalized handler for the case when an orchestration is suspended.
- Remove dealing with suspended orchestrations from all other event handlers.

2022-07-22 18:38 UTC, Julio-Arroyo commented on src/DurableTask.Core/SuspendedOrchestrationMessageInfo.cs
> +    class SuspendedOrchestrationMessageInfo
You are right! It's not needed, I've removed it.

2022-07-22 18:52 UTC, Julio-Arroyo commented on src/DurableTask.Core/TaskOrchestrationContext.cs
> +        private readonly Queue<HistoryEvent> eventsWhileSuspended;
Now that I got rid of the unnecessary class SuspendedOrchestrationMessageInfo and have centralized the logic of dealing with events while the orchestration is suspended to the ProcessEvent class, I have modified the naming of this buffer and I consider that everything is much more readable now so no need for comments that clutter the code.

2022-07-22 18:58 UTC, Julio-Arroyo commented on src/DurableTask.Core/TaskOrchestrationExecutor.cs
>          void ProcessEvent(HistoryEvent historyEvent)
Now the individual handlers do not deal with the suspended or running question, and all is done in a single place here. To keep the pattern of using handlers, I kept the function pointer to `ProcessEvent` in `HandleExecutionResumed`. @amdeel perhaps I misunderstood your question earlier about not passing along the function pointer, did you want me to recursively call `ProcessEvent` here instead?

2022-07-22 19:01 UTC, Julio-Arroyo commented on test/DurableTask.AzureStorage.Tests/AzureStorageScenarioTests.cs
> +        public async Task SuspendResumeCheckStatus()
Ok! I will consolidate them into a single test.

2022-07-25 21:59 UTC, davidmrdavid commented on test/DurableTask.Test.Orchestrations/SimpleOrchestrations.cs
> +            await context.CreateTimer<int>(context.CurrentUtcDateTime, 0);
@amdeel: is this required?

2022-07-25 22:03 UTC, Julio-Arroyo commented on src/DurableTask.Core/OrchestrationRuntimeState.cs
> +                return orchestrationStatus;
You are suggesting having no return value?

2022-07-25 22:07 UTC, davidmrdavid commented on test/DurableTask.AzureStorage.Tests/AzureStorageScenarioTests.cs
> +        }
Resolving this to help narrow down the remaining feedback.

2022-07-25 23:03 UTC, davidmrdavid commented on src/DurableTask.AzureServiceFabric/Remote/RemoteOrchestrationServiceClient.cs
> +        /// Suspends the specified orchestration instance
Since this doesn't seem to be a convention we've followed well across this file / project (I see this from just reviewing the methods right above and below), I'd personally suggesting not blocking on this.

2022-07-25 23:14 UTC, davidmrdavid approved these changes
LGTM / Looks good to me.
No further blockers on my part, but please wait for @amdeel's final word as she's the SME on this repo.

2022-07-26 22:06 UTC, Julio-Arroyo commented on src/DurableTask.Core/TaskOrchestrationExecutor.cs
> +                }
I added this condition based on @davidmrdavid 's suggestion, and as a fix to @amdeel 's concern about being resilient - at the Durable Task Framework level - that suspend "behaves appropriately when misused". In particular, here I avoid adding a Suspend event to the queue if the orchestrator is already suspended.

2022-08-03 15:33 UTC, amdeel reviewed
This looks great! Just a few more small changes.

2022-08-03 15:33 UTC, amdeel commented on src/DurableTask.Core/TaskOrchestrationExecutor.cs
> +                if (historyEvent.EventType != EventType.ExecutionSuspended)
You can make this one conditional instead of two.

nit: I'm not sure about the name "isWakingEvent." Aren't all events waking? But all not events override a suspended state.

2022-08-03 15:33 UTC, amdeel commented on test/DurableTask.AzureStorage.Tests/AzureStorageScenarioTests.cs
> +    using DurableTask.Test.Orchestrations;
The orchestrations should exist in the same class, you shouldn't need this.

2022-08-03 15:33 UTC, amdeel commented on test/DurableTask.AzureStorage.Tests/AzureStorageScenarioTests.cs
> +            using (TestOrchestrationHost host = TestHelpers.GetTestOrchestrationHost(enableExtendedSessions: true))
Make this test run when enableEtendedSessions is true and false by adding attributes to this test like "[DataRow(true)] [DataRow(false)]" instead of defaulting the parameter to true.

2022-08-03 15:33 UTC, amdeel commented on test/DurableTask.AzureStorage.Tests/AzureStorageScenarioTests.cs
> +            using (TestOrchestrationHost host = TestHelpers.GetTestOrchestrationHost(enableExtendedSessions: true))
Same comment about extended sessions.

2022-08-03 15:33 UTC, amdeel commented on test/DurableTask.AzureStorage.Tests/AzureStorageScenarioTests.cs
> +                string resumeMsg = "wakeUp";
These suspend and resume variables don't seem very important and are only used once. You can just use these strings in-line.

2022-08-03 15:33 UTC, amdeel commented on test/DurableTask.AzureStorage.Tests/AzureStorageScenarioTests.cs
> +
You should call WaitForCompletionAsync before stopping.

2022-08-03 18:08 UTC, Julio-Arroyo commented on src/DurableTask.Core/TaskOrchestrationExecutor.cs
> +                if (historyEvent.EventType != EventType.ExecutionSuspended)
It seems to me that this method should be in charge of re-directing the flow of execution based on the context, whereas the handlers should be the ones to incorporate the logic of dealing with messages. So, I have moved the second check into `HandleEventsWhileSuspended` (since its goal is to ignore suspend messages when an orchestrator is already suspended). As a result, we don't have a double check in this method.

I have renamed the `isWakingEvent` flag to `overrideSuspension` in an attempt to make it more descriptive. The reason we have this flag rather than putting all conditions in the same if statement, is based on @davidmrdavid 's feedback that if you do put it all together it becomes too long and hard to read and reason about.

2022-08-03 18:16 UTC, Julio-Arroyo commented on test/DurableTask.AzureStorage.Tests/AzureStorageScenarioTests.cs
> +            using (TestOrchestrationHost host = TestHelpers.GetTestOrchestrationHost(enableExtendedSessions: true))
done

2022-08-03 18:18 UTC, Julio-Arroyo commented on test/DurableTask.AzureStorage.Tests/AzureStorageScenarioTests.cs
> +                string resumeMsg = "wakeUp";
Sure

2022-08-03 18:21 UTC, Julio-Arroyo commented on test/DurableTask.AzureStorage.Tests/AzureStorageScenarioTests.cs
> +
Got it.

2022-08-03 23:58 UTC, davidmrdavid commented on src/DurableTask.Core/TaskOrchestrationExecutor.cs
> +                if (historyEvent.EventType != EventType.ExecutionSuspended)
@Julio-Arroyo: Since Amanda is the owner of this part of the code, please feel free to override my comment with her suggestion on this one.

2022-08-08 18:30 UTC, amdeel approved these changes
It's great to see this PR done! We'll want to wait for Chris's approval before merging. Congratulations on your first feature Julio!

2022-08-08 18:30 UTC, amdeel commented on test/DurableTask.AzureStorage.Tests/AzureStorageScenarioTests.cs
> +                var client = await host.StartOrchestrationAsync(typeof(Test.Orchestrations.NextExecution), "OGstatus");
Sorry for the confusion, you can pull out the definitions for the reused strings. WakeUp appears to be the only non-reused string here.

2022-08-08 18:30 UTC, amdeel commented on src/DurableTask.Core/History/EventType.cs
> +//       new EventTypes, append them at the end.
This sounds like an OOProc bug, though in general I agree that we would be adding new types to the end of this file.

2022-08-08 18:41 UTC, amdeel commented
/azp run

2022-08-09 00:24 UTC, amdeel commented
/azp run

2022-08-09 23:05 UTC, amdeel commented
/azp run

2022-08-10 23:41 UTC, cgillum requested changes
Some initial comments related to versioning that we'll need to take care of before merging this change.

2022-08-10 23:41 UTC, cgillum commented on Test/DurableTask.Stress.Tests/Properties/launchSettings.json
> +}
Does this file need to be included in the PR or can it be excluded? It doesn't seem related.

2022-08-10 23:41 UTC, cgillum commented on src/DurableTask.Core/IOrchestrationServiceClient.cs
> +        Task ResumeTaskOrchestrationAsync(string instanceId, string reason);
Adding methods to an interface is a breaking change in .NET. For example, if we release this change, it will cause compile errors to the MSSQL and Netherite backends if they try to update the version of DurableTask.Core that they use. This seems pretty dangerous to me, so I suggest we introduce this in a non-breaking way by doing the following:

1. Create a new interface called `IOrchestrationServiceSuspendResumeClient` that contains these two method signatures.
2. Update AzureStorageOrchestrationService to implement this new interface (should be a one-line change)
3. Remove the `NotImplementedException`s for the services that don't support this, like Service Fabric now that they're not required to implement the interface.
4. In TaskHubClient, instead of calling into `IOrchestrationServiceClient` directly, try to first cast the `IOrchestrationServiceClient` object into an `IOrchestrationServiceSuspendResumeClient` using the `is` or `as` operator. If the cast succeeds, call the appropriate Suspend/Resume method on the object. Otherwise, throw a `NotImplementedException`.
5. Depending on how you call this functionality from the Durable Extension (I haven't looked at that PR yet), you may need to do the same thing as (4) in the Durable extension code.

This is a bit more work but will allow us to release the feature as a non-breaking change.

2022-08-10 23:41 UTC, cgillum commented on src/DurableTask.Core/DurableTask.Core.csproj
> +    <PatchVersion>1</PatchVersion>
The `PatchVersion` is incremented only for internal bug fixes. For new (non-breaking) features, we need to update the `MinorVersion` instead.

2022-08-11 12:19 UTC, cgillum reviewed
Completed a full pass of the code. Really excited to see this feature come in! I made some changes to a previous comment I made about `IOrchestrationServiceClient` so please take a look at that and let me know if you have any questions.

2022-08-11 12:19 UTC, cgillum commented on src/DurableTask.Core/OrchestrationRuntimeState.cs
> +                orchestrationStatus = OrchestrationStatus.Running;
I think we should first check to see whether the orchestration is in a non-completed state before changing the status to `Running`. Otherwise, an `ExecutionResumedEvent` that gets received by a completed orchestration could potentially result in the orchestration set to the `Running` state, which would be incorrect and confusing. See the checks further above for other examples of where we do status sanity checks. I don't think we need to throw exceptions for this, but we should avoid setting the status to Running.

2022-08-11 12:19 UTC, cgillum commented on src/DurableTask.Core/TaskHubClient.cs
> +        public Task SuspendInstanceAsync(OrchestrationInstance orchestrationInstance)
Rather than creating two overloads, make a single overload with an optional `reason` parameter. This is the preferred design for modern .NET APIs.

Something like this:
```csharp
public async Task SuspendInstanceAsync(OrchestrationInstance orchestrationInstance, string reason = null)
{
    // ...
}
```

Same thing for `ResumeInstanceAsync`.

2022-08-11 12:19 UTC, cgillum commented on src/DurableTask.Core/TaskOrchestrationContext.cs
> +        public void HandleEventWhileSuspended(HistoryEvent historyEvent)
code style nit: please move this method below the constructor. This is a common practice for C# code (whoever added the `AddEventToNextIteration` method should have also followed this style guideline). Ideally it would be grouped with the other suspend/resume-related events.

2022-08-11 12:19 UTC, cgillum commented on src/DurableTask.Core/TaskOrchestrationContext.cs
> +        public void HandleEventRaisedEvent(HistoryEvent historyEvent, bool skipCarryOverEvents, TaskOrchestration taskOrchestration)
Shouldn't this method take `EventRaisedEvent` instead of `HistoryEvent`?

2022-08-11 12:19 UTC, cgillum commented on test/DurableTask.AzureStorage.Tests/AzureStorageScenarioTests.cs
> +                await Task.Delay(2000);
nit: it's best to avoid sleep/delays in test code as much as possible since they are a common source of test reliability issues. Instead, consider writing a method that checks the status in a loop and breaks only when the orchestration status is "Suspended" (or throw an exception if the status doesn't change after X amount of time).

2022-08-11 12:19 UTC, cgillum commented on test/DurableTask.AzureStorage.Tests/AzureStorageScenarioTests.cs
> +                await Task.Delay(2000);
Same comment as the above.

2022-08-11 12:19 UTC, cgillum commented on test/DurableTask.AzureStorage.Tests/AzureStorageScenarioTests.cs
> +                await Task.Delay(2000);
Same comment as above

2022-08-11 12:19 UTC, cgillum commented on test/DurableTask.AzureStorage.Tests/TestOrchestrationClient.cs
> +        public Task SuspendAsync(string reason)
Related to my previous comments, consider adding a flag parameter for waiting until the status changes before returning from this method.

2022-08-11 18:42 UTC, Julio-Arroyo commented on src/DurableTask.Core/History/ExecutionSuspendedEvent.cs
> +        /// <param name="reason">The serialized input of the termination event</param>
Fixed.

2022-08-11 18:43 UTC, Julio-Arroyo commented on src/DurableTask.Core/History/ExecutionSuspendedEvent.cs
> +    /// A history event for orchestration pause
Done.

2022-08-11 18:47 UTC, Julio-Arroyo commented on src/DurableTask.Core/TaskOrchestrationContext.cs
> +        public void HandleEventRaisedEvent(HistoryEvent historyEvent, bool skipCarryOverEvents, TaskOrchestration taskOrchestration)
Done.

2022-08-11 18:49 UTC, Julio-Arroyo commented on src/DurableTask.Core/TaskHubClient.cs
> +        public Task SuspendInstanceAsync(OrchestrationInstance orchestrationInstance)
fixed.

2022-08-11 19:14 UTC, Julio-Arroyo commented on src/DurableTask.Core/TaskOrchestrationContext.cs
> +        public void HandleEventWhileSuspended(HistoryEvent historyEvent)
Got it.

2022-08-11 21:53 UTC, Julio-Arroyo commented on src/DurableTask.Core/OrchestrationRuntimeState.cs
> +                orchestrationStatus = OrchestrationStatus.Running;
`ExecutionCompletedEvent` should be null as long as the orchestration is not completed right? I have used it for this check. Let me know if you don't think that would be resilient enough.

2022-08-11 21:57 UTC, Julio-Arroyo commented on src/DurableTask.AzureStorage/AzureStorageOrchestrationService.cs
> +                runtimeState.OrchestrationStatus != OrchestrationStatus.Suspended)
Oh, great point. Thanks for bringing it up.

2022-08-12 00:13 UTC, cgillum reviewed
Looking much better! Just a couple more things.

2022-08-12 00:13 UTC, cgillum commented on src/DurableTask.Core/OrchestrationRuntimeState.cs
>              }
It doesn't feel right to me to have two sources of truth for what the orchestration status is (this new `orchestrationStatus` variable and also the `ExecutionCompletedEvent` property). To reduce overall complexity, I suggest you get rid of the ExecutionCompletedEvent != null check (and the return statement inside it) and always return the value of `orchestrationStatus` here. Also, update `SetMarkerEvents` with logic that will update `orchestrationStatus` when `historyEvent is ExecutionCompletedEvent completedEvent`. This way, `orchestrationStatus` becomes the single source of truth which is only updated inside `SetMarkerEvents`.

2022-08-12 00:13 UTC, cgillum commented on src/DurableTask.Core/DurableTask.Core.csproj
> +    <PatchVersion>1</PatchVersion>
Friendly reminder to update this. The new version should be 2.11.0 since we're adding a new feature.

2022-08-12 17:26 UTC, cgillum commented on src/DurableTask.Core/OrchestrationRuntimeState.cs
> -                ExecutionCompletedEvent = completedEvent;
I think this code you removed needs to be added back.

2022-08-12 17:31 UTC, Julio-Arroyo commented on src/DurableTask.Core/OrchestrationRuntimeState.cs
> -                ExecutionCompletedEvent = completedEvent;
Added it back.

2022-08-12 17:32 UTC, Julio-Arroyo commented on src/DurableTask.Core/OrchestrationRuntimeState.cs
>              }
Got it. Changes should be in place.

2022-08-12 17:32 UTC, Julio-Arroyo commented on src/DurableTask.Redis/DurableTask.Redis.csproj
> +    <FileVersion>0.1.10</FileVersion>
Done.

2022-08-12 17:49 UTC, Julio-Arroyo commented on src/DurableTask.Core/DurableTask.Core.csproj
> +    <PatchVersion>1</PatchVersion>
Got it.

2022-08-12 20:35 UTC, cgillum commented on src/DurableTask.Core/OrchestrationRuntimeState.cs
> +                orchestrationStatus = OrchestrationStatus.Completed;
I believe this needs to be `completedEvent.OrchestrationStatus`, just like it was in the previous implementation of `SetMarkerEvents()`. Otherwise, orchestration failure won't be handled correctly. This is because `ExecutionCompletedEvent` handles multiple forms of completion, including failure.

2022-08-12 23:21 UTC, cgillum commented
/azp run

2022-08-13 00:03 UTC, cgillum approved these changes
Changes look good to me and the CI is passing, so signing off on this! Since this is a big change that touches the core engine, let's verify that the scenario is working as expected in the extension repo before merging this change.

2022-08-15 20:27 UTC, davidmrdavid commented
<3 thanks @amdeel and @cgillum for the detailed reviews. Will work with @Julio-Arroyo to make sure this works as expected in the Extension prior to the merge

2022-08-17 19:10 UTC, Julio-Arroyo commented
/azp run

2022-08-17 19:16 UTC, cgillum commented
/azp run

2022-08-17 21:08 UTC, davidmrdavid commented
/azp run

2022-08-17 23:36 UTC, Julio-Arroyo commented on src/DurableTask.AzureStorage/AzureStorageOrchestrationService.cs
> +                runtimeState.OrchestrationStatus != OrchestrationStatus.Suspended)
@cgillum  Actually, I want to argue that we _do_ need this change: `runtimeState.OrchestrationStatus != OrchestrationStatus.Suspended` must be included. (@davidmrdavid this is the bug we were unable to explain earlier today).

`isExecutableInstance` has one single reference. It is used by `AzureStorageOrchestrationService.cs` to check whether the batch of messages dequeued should be discarded or abandoned. If we do not include this extra check, there are many scenarios where this feature won't work. Consider the following two examples:

1. Consider a suspended orchestration. The client tries to raise an event. Thus, that message is enqueued, later dequeued. If we don't add `runtimeState.OrchestrationStatus != OrchestrationStatus.Suspended`, `isExecutableInstance` will return false. Which means that the `RaiseEvent` will be discarded and will not make it to the history.
2. Similarly, if you have a suspended orchestration, and try to terminate it, the `TerminateEvent` message will be also discarded. So the terminate operation wouldn't work on suspended orchestrations.

@cgillum I know you mentioned you worry about potential problems this change could introduce. Could you elaborate on that?

2022-08-17 23:44 UTC, cgillum commented on src/DurableTask.AzureStorage/AzureStorageOrchestrationService.cs
> +                runtimeState.OrchestrationStatus != OrchestrationStatus.Suspended)
@Julio-Arroyo Ah, I see. I was reading the logic backwards and thought we'd discard the message if it was in a suspended state. You're right - we need the suspended check here to avoid unnecessarily discarding work items for suspended instances.

2022-08-17 23:50 UTC, cgillum commented
I just took a look at the CI results, and it looks like tests never actually ran!  We need to investigate what's going on, and whether it's just this PR or if other PRs have the same problem.

2022-08-18 00:03 UTC, cgillum commented
I think the CI may have been silently broken since this PR back in April: https://github.com/Azure/durabletask/pull/707. Basically, our CI filters the list of test assemblies using folder paths. When we changed the TFM from `net461` to `net462` for the test projects, that changed the folder paths. As a result, the CI wouldn't find any test assemblies and simply marked the run as "passed" since nothing failed (problem is, no tests passed either).

I've fixed the problem with the CI configuration and will try re-running the CI. If we're lucky, it will pass, but it's possible that a regression may have snuck in from some other PR during the time that the tests were silently disabled.

2022-08-18 00:04 UTC, cgillum commented
/azp run

2022-08-18 01:37 UTC, cgillum commented
Looks like some existing tests not related to this PR is failing.

![image](https://user-images.githubusercontent.com/2704139/185272752-805921fe-0398-47f8-a58c-1d05d3526c7e.png)

My guess is that the regression was caused by https://github.com/Azure/durabletask/pull/750. I verified by debugging locally that at least one of these tests fail consistently. The regression has not shipped yet so the problem doesn't exist out in the wild, but it's unfortunately a blocker for this release. I'll contact the contributor to see if they can fix the issue. Worst case scenario is that we have to revert their changes to get the CI green again.

2022-08-18 18:59 UTC, cgillum commented
/azp run

2022-08-18 22:35 UTC, merged