Propagating OrchestrationRuntimeState to TaskActivity
Azure/durabletask pull request #804
Opened 2022-10-12 02:49 UTC by RamjotSingh

Propagating OrchestrationRuntimeState to TaskActivity dispatcher middleware. This allows Tags and other historical events to be accessible from TaskActivity dispatcher middleware

2022-10-12 03:54 UTC, cgillum commented on src/DurableTask.Core/TaskOrchestrationDispatcher.cs
> +            taskMessage.OrchestrationRuntimeState = runtimeState;
The runtime state can potentially be huge, so we should never attach it to messages. Instead, we should attach the most limited amount of data we need for the scenario.

2022-10-12 08:48 UTC, RamjotSingh commented on src/DurableTask.Core/TaskOrchestrationDispatcher.cs
> +            taskMessage.OrchestrationRuntimeState = runtimeState;
Created a new object and put just Tags in it for now. Made it available in both Orchestration and Activity.

2022-10-12 17:21 UTC, cgillum commented on src/DurableTask.Core/TaskOrchestrationDispatcher.cs
> +            return new OrchestrationExecutionContext { OrchestrationTags = runtimeState.Tags ?? new Dictionary<string, string>() };
I wonder if it would be better to allow this property to be `null` to avoid unnecessary allocations. Alternatively, we should initialize it with a capacity of zero (`new Dictionary<string, string>(capacity: 0)`).

2022-10-12 17:21 UTC, cgillum commented on src/DurableTask.Core/OrchestrationExecutionContext.cs
> +        public IDictionary<string, string> OrchestrationTags { get; internal set; } = new Dictionary<string, string>();
It looks like we're always assigning this property eternally at construction time, so the default initialization is being wasted. I suggest removing that. I also suggest we make this an `IReadOnlyDictionary<string, string>` since developers should never be adding to it themselves.
```csharp
public IReadOnlyDictionary<string, string>? OrchestrationTags { get; internal set; }
```

2022-10-12 18:29 UTC, jviau requested changes
This looks good. But can you add a test case for the migration window? Where an existing activity does not have `OrchestrationExecutionContext` serialized - what does that look like in middleware? Ensure it doesn't cause any regressions.

2022-10-12 20:38 UTC, RamjotSingh commented on src/DurableTask.Core/OrchestrationExecutionContext.cs
> +        public IDictionary<string, string> OrchestrationTags { get; internal set; } = new Dictionary<string, string>();
Made it IReadonlyDictionary but havent made it nullable since we will always assign value from public access standpoint

2022-10-13 10:29 UTC, RamjotSingh commented on test/DurableTask.Core.Tests/DispatcherMiddlewareTests.cs
> +        public async Task EnsureActivityDispatcherMiddlewareHasAccessToRuntimeState()
Done.

2022-10-13 10:30 UTC, RamjotSingh commented on src/DurableTask.Core/TaskOrchestrationDispatcher.cs
> +            return new OrchestrationExecutionContext { OrchestrationTags = runtimeState.Tags ?? new Dictionary<string, string>() };
Fixed.

2022-10-13 16:15 UTC, jviau approved these changes
Looks good!

2022-10-13 20:26 UTC, cgillum approved these changes
LGTM!

2022-10-13 20:29 UTC, merged