OpenTelemetry instrumentation for sub-orchestrations
Azure/durabletask pull request #825
Opened 2022-11-16 21:08 UTC by bachuv

This PR updates OTel instrumentation for sub-orchestrations. There are now separate spans for scheduling a sub-orchestration and executing a sub-orchestration.

**Sample orchestration**
```
class HelloSubOrch : TaskOrchestration<string, string>
{
    public override async Task<string> RunTask(OrchestrationContext context, string input)
    {
        string result = "";
        result += await context.CreateSubOrchestrationInstance<string>(typeof(HelloSequence), null);
        result += await context.ScheduleTask<string>(typeof(SayHello), "Tokyo");
        result += context.CreateSubOrchestrationInstance<string>(typeof(HelloFanOut), null);
        result += await context.CreateSubOrchestrationInstance<string>(typeof(HelloSequence), null);
        return result;
    }
}
```
**Related Gantt charts**
Application Insights
![image](https://user-images.githubusercontent.com/15795068/202287059-908163b4-d082-4d53-b4cf-23b4961e455d.png)

Zipkin
![image](https://user-images.githubusercontent.com/15795068/202287088-c0fe967d-af8d-408e-9b69-adc0b488f2b4.png)

2022-11-16 23:43 UTC, jviau commented
Couple questions regarding the Gantt diagram:

1. Do we need the index on the dependency telemetry? The `(#1)`, `(#2)` suffixes? The fact they are different spans (with different SpanId's) should already correctly differentiate them. What value do we get out of them?
    - We should be referencing the OTel spec for how to name spans anyways. So, we may have more changes then just this.
2.  Why is the duration for all the sub orchestration dependency (client) telemetry 0? This should be the duration between first enqueueing the sub orchestration and when you are finally replayed with the completed sub orchestration.
3. Are the `TaskActivity` server spans coming in a later PR?

2022-11-17 01:07 UTC, cgillum commented
> Do we need the index on the dependency telemetry? The (#1), (#2) suffixes? The fact they are different spans (with different SpanId's) should already correctly differentiate them. What value do we get out of them?

These are the task IDs. They are the same value as the `dtfx.task_id` properties. It's not critical for them to be in the name. We should definitely *not* include them when their values are `-1` though (-1 means that task ID doesn't apply).

2022-11-17 19:13 UTC, jviau commented
I think we should leave task ID off the span name. Here is some OTel guidance on span naming: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md#span With the relevant part being:

> The span name SHOULD be the most general string that identifies a (statistically) interesting class of Spans, rather than individual Span instances while still being human-readable.

To me, including task ID starts encroaching into "individual Span instances" naming and not "class of Spans".

2022-11-17 19:38 UTC, cgillum commented
I'm fine with that. However, it begs another question: should the activity spans be named after the activity type being invoked or should it simply be "Activity"?

2022-11-17 20:58 UTC, jviau commented
Looking at the HTTP request example, I would say a third option: it should be named with the task name it was enqueued with. But then we also have version, and do we want to also include task type in the span name? We have three potential pieces to include: `taskType`, `taskName`, and `taskVersion`. Which ones do we want to include and in what format? Some ideas:

All three: `{taskType}|{taskName}(|{taskVersion})?` (so when `taskVersion` is `null`, we leave it off)
Type and name: `{taskType}|{taskName}` - version will still be an attribute.
Just name: `{taskName}` - version and type will be an attribute.

I am using `|` as a separator, but open to other separators. I wanted something that would not be in a type name (of any language), but is not confused with other spans (ie: http uses `/`, so `orchestration/myOrchestration/2` looks like a HTTP route span), and also is not going to cause encoding or support problems on various telemetry services.

2022-11-17 21:11 UTC, cgillum commented
I'm fine with `|`, though I find it's often hard to read. I do prefer `/` but I understand that you want to avoid confusing this with HTTP. Maybe `||`? I also like your suggestion about type + name + version, so something like `Activity||SayHello` (which has no version) seems good to me.

2022-11-18 00:04 UTC, bachuv commented
@jviau

> 1. Do we need the index on the dependency telemetry? The `(#1)`, `(#2)` suffixes? The fact they are different spans (with different SpanId's) should already correctly differentiate them. What value do we get out of them?
>     - We should be referencing the OTel spec for how to name spans anyways. So, we may have more changes then just this.

I'll remove the task IDs and update it to `{taskType}|{taskName}`.

> 2.  Why is the duration for all the sub orchestration dependency (client) telemetry 0? This should be the duration between first enqueueing the sub orchestration and when you are finally replayed with the completed sub orchestration.

I'll update the instrumentation so the duration includes the time from when it's enqueued to when it actually completes.

> 3. Are the `TaskActivity` server spans coming in a later PR?

Yes

2022-12-02 21:34 UTC, jviau commented
The duration of the sub-orchestration `client` span doesn't look correct to me. It should always be strictly _longer_ than the `server` span for that sub orchestration. The importance of this is you want to see the time delay difference between "here is how long I waited for my sub orchestration" vs "here is how long that sub orchestration actually ran". The gaps between `client` and `server` respective start times and their respective end times has significance.

2022-12-12 22:34 UTC, jviau requested changes

2022-12-12 22:34 UTC, jviau commented on src/DurableTask.Core/TaskOrchestrationDispatcher.cs
> +            activity.Stop();
As mentioned in my other comment, the duration of this activity should represent how long this orchestration was waiting on the sub orchestration complete.

2022-12-12 22:34 UTC, jviau commented on src/DurableTask.Core/TaskOrchestrationDispatcher.cs
> +            activity.Stop();
This activity should also have success/error information populated as well `exception.*` tags as necessary depending on how the sub-orchestration failed (if it did fail).

2023-01-04 17:54 UTC, bachuv commented on src/DurableTask.Core/TaskOrchestrationDispatcher.cs
> +            using Activity activity = TraceHelper.StartTraceActivityForSubOrchestration(startedEvent);
I tried using Activity.Current to get the parent, but it doesn't exist in the context where the sub-orchestration span is created in ReconcileMessagesWithState(). The method is called after the end of the sub-orchestration execution and before the parent orchestration state is restored (which restores Activity.Current). I ended up storing the parent trace context instead of the entire ExecutionStartedEvent.

2023-01-04 17:55 UTC, bachuv commented on src/DurableTask.Core/Tracing/TraceHelper.cs
> +                    new("dtfx.type", "orchestrator"),
I'll make those changes in a separate PR.

2023-01-05 18:12 UTC, jviau commented on src/DurableTask.Core/History/SubOrchestrationInstanceCompletedEvent.cs
> +        public DateTime StartTime { get; set; }
Is it possible for us to avoid storing this, and instead find the pairing `SubOrchestrationInstanceCreatedEvent` to get the start time?

2023-01-07 00:01 UTC, jviau commented on src/DurableTask.Core/TaskOrchestrationDispatcher.cs
> +                if (message.Event is SubOrchestrationInstanceCompletedEvent completedEvent && completedEvent.Name != null && completedEvent.ParentTraceContext != null && completedEvent.StartTime != n
May want to simplify this if statement a bit, especially if we also need to start also considering `SubOrchestrationInstanceFailedEvent`.

1. Can use pattern matching, syntax may not be 100%, but try: `if (message.Event is SubOrchestrationInstanceCompletedEvent completedEvent { Name: not null, ParentTraceContext: not null, StartTime: not null })`
2. Or, should we extract a common interface for completed and failed events which contain all the relevant information? Can test for that and pass to the `TraceHelper` method. Something like:

``` CSharp
if (message.Event is ISubOrchestratrionFinishedEvent orchestrationEvent)
{
    TraceHelper.StartTraceActivityForSubOrchestrationFinished(workItem.OrchestrationRuntimeState.OrchestrationInstance, orchestrationEvent)?.Dispose();
}
}
```

2023-01-11 19:10 UTC, bachuv commented on src/DurableTask.Core/History/SubOrchestrationInstanceCompletedEvent.cs
> +        public DateTime StartTime { get; set; }
I tried to find the corresponding `SubOrchestrationInstanceCreatedEvent`, but wasn't able to. @cgillum do you know if it's possible to get a sub-orchestration's `SubOrchestrationInstanceCreatedEvent` by looking at its `SubOrchestrationInstanceCompletedEvent`?

2023-01-11 19:10 UTC, bachuv commented on src/DurableTask.Core/TaskOrchestrationDispatcher.cs
> +                if (message.Event is SubOrchestrationInstanceCompletedEvent completedEvent && completedEvent.Name != null && completedEvent.ParentTraceContext != null && completedEvent.StartTime != n
I created the common interface and kept the validation checks in the if statement before it calls `StartTraceActivityForSubOrchestrationFinished()`. I kept the validation checks there to avoid calling the TraceHelper method any time there's a `SubOrchestrationInstanceCompletedEvent` or `SubOrchestrationInstanceFailedEvent`. Let me know if any improvements can be made here.

2023-01-11 20:01 UTC, bachuv commented on src/DurableTask.Core/TaskOrchestrationDispatcher.cs
> +                    if (Activity.Current != null)
Adding a note here to handle the fire and forget scenario.

2023-01-11 20:04 UTC, jviau commented on src/DurableTask.Core/TaskOrchestrationDispatcher.cs
> +                if (message.Event is SubOrchestrationInstanceCompletedEvent completedEvent && completedEvent.Name != null && completedEvent.ParentTraceContext != null && completedEvent.StartTime != n
Looks great! I do recommend moving the check into the `TraceHelper` method. This keeps the details of when/what/how we perform this trace together in one place. But it is up to you.

2023-01-11 22:00 UTC, jviau requested changes

2023-01-11 22:00 UTC, jviau commented on src/DurableTask.Core/Tracing/TraceHelper.cs
> +            List<KeyValuePair<string, object?>> activityTags = new List<KeyValuePair<string, object?>>
For optimization, we should create the activity first (line 188), then append tags only if non-null. If the activity is null, we can return immediately and avoid allocations.

2023-01-12 00:40 UTC, jviau commented on src/DurableTask.Core/History/SubOrchestrationInstanceCompletedEvent.cs
> +        public DateTime StartTime { get; set; }
I think you can find it via:

``` CSharp
workItem.OrchestrationRuntimeState.Events.FirstOrDefault(x => x.EventId == {TaskScheduledId});
```

Where `TaskScheduledId` is the property found on both `SubOrchestrationInstanceFailedEvent` and `SubOrchestrationInstanceCompletedEvent` (so can move it to the interface). And `workItem` is the parameter in `ReconcileMessagesWithState`

2023-01-18 19:43 UTC, bachuv commented on src/DurableTask.Core/Tracing/TraceHelper.cs
> +                activityTags.Add(new KeyValuePair<string, object?>("dtfx.details", failedEvent.Details));
That makes sense. I will update this. I remember that we decided against stack trace because there could be sensitive information.

2023-01-18 19:46 UTC, bachuv commented on src/DurableTask.Core/TaskOrchestrationDispatcher.cs
> +                if (message.Event is SubOrchestrationInstanceCompletedEvent completedEvent && completedEvent.Name != null && completedEvent.ParentTraceContext != null && completedEvent.StartTime != n
Ok, I can move the validation into the `TraceHelper` method.

2023-01-18 23:14 UTC, jviau commented on src/DurableTask.Core/Tracing/TraceHelper.cs
> +                activityTags.Add(new KeyValuePair<string, object?>("dtfx.details", failedEvent.Details));
Yeah it might, so we want to make sure it is configurable.

1. Introduce some way to configure durable task instrumentation. We can discuss this later. We may want other things configurable. We can definitely include a "options" callback for the OTel extension method we eventually include.
2. OTel exporters typically also have their own way to control stack trace exporting - as long as we use the correct attribute name, they typically have ways to ignore exporting of stack trace.

2023-01-20 17:10 UTC, bachuv commented on src/DurableTask.Core/TaskOrchestrationDispatcher.cs
> +                    if (Activity.Current != null)
How should we handle instrumenting/showing the execution of a fire and forget sub-orchestration? Since it's fire and forget, we don't await the execution completion which means that the orchestration execution might complete or might not within the same process. 

I'm noticing that if there's an await after a fire and forget sub-orchestration call, then the orchestration execution is captured and emitted (in the simple test code). If there is no await (the fire and forget call is the last step in the orchestration), then we either see nothing about the orchestration execution or we see a partial execution (one activity call span, but this has the incorrect parent [highlighted in image below]). 

I might be misunderstanding how fire and forget works so please correct me if I'm wrong. I also pushed these changes as a recent commit if anyone wants to refer to the instrumentation code I added for fire and forget sub-orchestrations.

```
class FireAndForgetSubOrchestration : TaskOrchestration<string, string>
{
    public override async Task<string> RunTask(OrchestrationContext context, string input)
    {
        string result = "";
        result += await context.CreateSubOrchestrationInstance<string>(typeof(HelloSequence), null);
        context.CreateSubOrchestrationInstance<object>(NameVersionHelper.GetDefaultName(typeof(HelloFanOut)), "", "1", null, new Dictionary<string, string>() { { OrchestrationTags.FireAndForget, "" } });
        context.CreateSubOrchestrationInstance<object>(NameVersionHelper.GetDefaultName(typeof(HelloSequence)), "", "2", null, new Dictionary<string, string>() { { OrchestrationTags.FireAndForget, "" } });
        context.CreateSubOrchestrationInstance<object>(NameVersionHelper.GetDefaultName(typeof(HelloSequence)), "", "3", null, new Dictionary<string, string>() { { OrchestrationTags.FireAndForget, "" } });
        return result;
    }
}
```

<img width="900" alt="image" src="https://user-images.githubusercontent.com/15795068/213760877-5c00ee92-249b-4de7-bb98-18c8ab659e74.png">

2023-01-20 17:12 UTC, bachuv commented on src/DurableTask.Core/TaskOrchestrationDispatcher.cs
> +            Activity traceActivity = TraceHelper.StartTraceActivityForExecution(startEvent);
This is used to restore the current Activity before going through the new messages. It's restored here to give the spans that are created in `ReconcileMessagesWithState()` an accurate parent Activity.

2023-01-20 17:16 UTC, bachuv commented on src/DurableTask.Core/TaskOrchestrationDispatcher.cs
> +                    traceActivity = TraceHelper.StartTraceActivityForExecution(runtimeState.ExecutionStartedEvent);
This is used to restore the current Activity for sub-orchestrations. I added it to the end of the do clause (after line 555) since it's already restored on line 310, but it looks like the orchestration state gets modified and the spans don't emit correctly.

2023-01-20 18:07 UTC, cgillum commented on src/DurableTask.Core/TaskOrchestrationDispatcher.cs
> +                    if (Activity.Current != null)
I would expect that a fire-and-forget sub-orchestration would show as completed after the sub-orchestration completed, which means it might live outside the scope of the parent orchestration. I'm not sure what that translates to in terms of implementation, but that's the picture I'd expect to see. If you're seeing that nothing gets emitted ever, then I wonder if we need to revisit something more fundamental about how we're tracking the start and end of trace spans.

That said, I'm okay with punting that to a separate PR. Fire-and-forget is not a common scenario (the Durable Task Framework doesn't really support it, actually, so the behavior is a bit undefined). I'm okay if we get the main sub-orchestration scenario working and do the edge cases separately.

2023-01-20 18:47 UTC, jviau commented on src/DurableTask.Core/TaskOrchestrationDispatcher.cs
> +                    traceActivity = TraceHelper.StartTraceActivityForExecution(runtimeState.ExecutionStartedEvent);
Slightly worried about this line in combination with line `310`, where `traceActivity` is originally set. Mostly worried about a case where we run line 310 then immediately run this line. What are the implications of essentially starting this activity twice? Do we need to clean up the old one first? Or should we skip this line on the first pass here?

2023-01-20 18:47 UTC, jviau commented on src/DurableTask.Core/TaskOrchestrationDispatcher.cs
> +                    if (Activity.Current != null)
Agree with punting it to another PR.

I also think it does have to do with _when_ we are emitting the span. I can say though it is incorrect to _not_ `await` the fire & forget. Even if it is fire & forget, you should still `await` it in case the framework is doing _some_ work behind the scenes.

2023-01-20 18:47 UTC, jviau commented on src/DurableTask.Core/Tracing/TraceHelper.cs
> +                Exception cause = Utils.RetrieveCause(failedEvent.Details, new JsonDataConverter());
Oh, this may be problematic. Customers can change how error details are converted, but we probably do not have access to that converter at this point. Not entirely sure what to do here. Do we leave this in? Or only retain `otel.status_code` for now and address this later? There is a legitimate concern where the customization of error data conversion would cause this to throw if we try and deserialize without having the proper converter.

2023-01-20 19:00 UTC, cgillum reviewed
Added some comments. One problem I'm anticipating is that this branch is really out of date and missing several other changes that have been made. We may need to rebase these PRs.

2023-01-20 19:00 UTC, cgillum commented on src/DurableTask.Core/TaskOrchestrationDispatcher.cs
> +                TraceHelper.CreateActivityForFireAndForgetSubOrchestration(historyEvent, runtimeState.OrchestrationInstance, parentTraceActivity)?.Dispose();
This seems like a really strange thing to do. I wonder if there's a better way to represent this - perhaps an OTel event of some kind? Having a span feels meaningless since there is no end time associated with this.

2023-01-20 21:19 UTC, jviau commented on src/DurableTask.Core/TaskOrchestrationDispatcher.cs
> +                TraceHelper.CreateActivityForFireAndForgetSubOrchestration(historyEvent, runtimeState.OrchestrationInstance, parentTraceActivity)?.Dispose();
While the duration will be very small, nearly 0, it does have meaning still. It will be a `Producer` span to convey meaning that this orchestration has kicked off a fire & forget. I think it is important to keep this as a span as it will maintain the chain of `Orchestration (Server) -> Fire & Forget (Producer) -> Orchestration (Server)`.

For OTel event, spans do have events, but I think a producer span here is still important so that users can distinguish between _multiple_ fire & forgets in the same orchestration, because then we get the parent-child relationship I mentioned. It would be ideal for this producer span, and several other spans, to include the actual work of the `IOrchestrationServicer` in it, but that will be challenging to do with the current structure of this code.

2023-01-24 02:30 UTC, bachuv commented on src/DurableTask.Core/TaskOrchestrationDispatcher.cs
> +                    if (Activity.Current != null)
I reverted those changes and will open a new PR for fire and forget scenarios once this PR is merged. I'll look into where we are emitting that span in the new PR and look for a more accurate place.

2023-01-24 02:31 UTC, bachuv commented on src/DurableTask.Core/TaskOrchestrationDispatcher.cs
> +                    traceActivity = TraceHelper.StartTraceActivityForExecution(runtimeState.ExecutionStartedEvent);
I was actually able to remove it, so we don't need to worry about this.

2023-01-24 02:32 UTC, bachuv commented on src/DurableTask.Core/Tracing/TraceHelper.cs
> +                Exception cause = Utils.RetrieveCause(failedEvent.Details, new JsonDataConverter());
I pulled the latest from `main` and added details based on the `FailureDetails` property.

2023-01-24 02:33 UTC, bachuv commented on src/DurableTask.Core/Tracing/TraceHelper.cs
> +            ISubOrchestrationFinishedEvent finishedEvent,
This interface isn't necessary anymore since we are restoring the "current" `Activity` (parent orchestration) before creating spans for completed or failed sub-orchestrations. It was used in a previous iteration to manually get the parent's trace context. I deleted the interface.

2023-01-25 23:29 UTC, jviau approved these changes
I take it the fire & forget logic is being left for another time?

2023-01-25 23:48 UTC, bachuv commented
Yes, I removed it from this PR and will work on it at another time.

2023-01-26 00:53 UTC, cgillum reviewed
A could tiny cleanup things and then just one small refactor and I'm ready to sign off on this PR.

2023-01-26 00:53 UTC, cgillum commented on src/DurableTask.Core/History/SubOrchestrationInstanceCompletedEvent.cs
> +    using DurableTask.Core.Tracing;
Non-blocking, but it looks like this whole file can be reverted (I assume these new `using` statements aren't necessary).

2023-01-26 00:53 UTC, cgillum commented on src/DurableTask.Core/History/SubOrchestrationInstanceFailedEvent.cs
> +    using DurableTask.Core.Tracing;
Non-blocking, but it looks like this whole file can be reverted (I assume these new `using` statements aren't necessary).

2023-01-26 00:53 UTC, cgillum commented on src/DurableTask.Core/TaskOrchestrationDispatcher.cs
> +                        TraceHelper.StartTraceActivityForSubOrchestrationFinished(workItem.OrchestrationRuntimeState.OrchestrationInstance, subOrchestrationCreatedEvent)?.Dispose();
Given that we will _always_ immediately call dispose on the trace activity that's returned from this method, I suggest we rename this method to `EmitTraceActivityForSubOrchestrationFinished`, have it return `void`, and do the `Dispose()` inside the implementation. That will make the intent of the code more clear.

2023-01-26 19:01 UTC, bachuv commented on src/DurableTask.Core/TaskOrchestrationDispatcher.cs
> +                        TraceHelper.StartTraceActivityForSubOrchestrationFinished(workItem.OrchestrationRuntimeState.OrchestrationInstance, subOrchestrationCreatedEvent)?.Dispose();
I made the same changes for Timers since they follow the same pattern.

2023-01-26 19:04 UTC, cgillum approved these changes
Latest iteration looks good to me!

2023-01-26 19:22 UTC, merged