Add Activity client spans
Azure/durabletask pull request #849
Opened 2023-01-20 17:43 UTC by bachuv

This PR adds spans that represent the time between when an Activity is called and finished. These are client spans.

For now, the target branch is "vabachu/otelsuborchupdates" to get the latest instrumentation code, but that branch is being updated in another PR. Before merging, the target branch should be "cgillum/opentelemetry"

Example:

The highlighted span is an example of the new client span for Activities.
<img width="911" alt="image" src="https://user-images.githubusercontent.com/15795068/213766801-ad6a35d1-c345-4202-98f2-9051318410b4.png">

2023-01-25 23:27 UTC, jviau commented on src/DurableTask.Core/TaskOrchestrationDispatcher.cs
> +                    TaskScheduledEvent taskScheduledEvent = (TaskScheduledEvent)workItem.OrchestrationRuntimeState.Events.FirstOrDefault(x => x.EventId == taskCompletedEvent.TaskScheduledId);
Will also need to handle `TaskFailedEvent`, similar to `SubOrchestrationFailedEvent`.

2023-01-26 00:59 UTC, cgillum reviewed
I like how small this PR is. :). Just one comment in addition to Jacob's.

2023-01-26 00:59 UTC, cgillum commented on src/DurableTask.Core/Tracing/TraceHelper.cs
> +                name: taskScheduledEvent.Name,
According to the spec, this should be `activity||{activityName}(||{orchestrationVersion})?`, right?

2023-01-27 17:21 UTC, bachuv commented on src/DurableTask.Core/TaskOrchestrationDispatcher.cs
> +                if (message.Event is TaskCompletedEvent taskCompletedEvent)
I noticed that when I was testing these changes that there are missing spans when workItem.NewMessages > 1 (e.g. multiple activities are scheduled using Task.WhenAll() for the Fan Out Fan In pattern).



This is the flow that I was observing:

1. For the first message in the list, Activity.Current != null so the parent context is set correctly. 
2. Then, the Activity is created (e.g. Activity for TaskCompletedEvent). After the Activity is disposed (newActivity.Dispose()), then Activity.Current is null. 
3. For all remaining messages, they will not go in the if block on line 742. Even if I remove that check for Activity.Current != null, I don't think the parent would be set correctly since Activity.Current is null and the parent trace context isn't stored anywhere.



When I was testing a Fan Out Fan In scenario, I was only seeing a client span for the first activity since the Activity was being disposed after the getting emitted. To work around this, I stored the ParentTraceContext to TaskScheduledEvent and read that in ReconcileMessagesWithState(). I know we are trying to avoid storing the parent trace context in the HistoryEvent, but I wasn't sure how to get around this without Activity.Current. I don't think restoring Activity.Current while iterating through the NewMessages is good practice.



I have a couple of questions:

1. I handled the case for activities by not checking for Activity.Current and manually setting the parent trace context, but this could happen in many other situations right? For any Task.WhenAllI() in an orchestration for example?
2. Does anyone have any suggestions/pointers on how we can avoid storing the parent trace context in TaskScheduledEvent?

2023-01-27 17:37 UTC, bachuv commented
The commit history got automatically updated because the target branch got deleted btw. It was originally vabachu/suborchupdates, but then that branch got deleted since the related PR was merged so the target branch is now cgillum/opentelemetry. That automatically added some commits to this PR which I didn't realize would happen, but makes sense. (I'm learning a lot about how git works through these distributed tracing PRs (: ) The diff between cgillum/opentelemetry and this PR should be accurate now though so ignore the number of commits please (:

2023-01-27 18:23 UTC, jviau commented
> The commit history got automatically updated because the target branch got deleted btw. It was originally vabachu/suborchupdates, but then that branch got deleted since the related PR was merged so the target branch is now cgillum/opentelemetry. That automatically added some commits to this PR which I didn't realize would happen, but makes sense. (I'm learning a lot about how git works through these distributed tracing PRs (: ) The diff between cgillum/opentelemetry and this PR should be accurate now though so ignore the number of commits please (:

Did you do a squash merge of `vabachu/suborchupdates` to `cgillum/opentelemetry.`? If so, that would explain this. The squash merge doesn't merge in each individual commit, but a new commit which is all the commits squashed down. If you try and merge those same commits back in, git doesn't know that squashed commit contains them. This isn't a big deal. If you merge in again with another squash commit it will all be fine. If it does bother you, you can use `git rebase -i` on your branch and drop all the commits already contained in the previous PR and only pick your new ones.

2023-01-27 19:02 UTC, cgillum commented on src/DurableTask.Core/TaskOrchestrationDispatcher.cs
> +                if (message.Event is TaskCompletedEvent taskCompletedEvent)
I'll go back and take a look at how I solved this in `durabletask-go`, but intuitively, I think the only place you need to store the parent trace context is in the `ExecutionStartedEvent` event. The fact that .NET uses thread-local variables probably makes tracking spans a lot harder than it needs to be, but I suspect each time we do a Dispose(), we need to reset `Activity.Current` to be the parent context that we already have in the `ExecutionStartedEvent`.

2023-01-27 19:13 UTC, cgillum commented on src/DurableTask.Core/TaskOrchestrationDispatcher.cs
> +                if (message.Event is TaskCompletedEvent taskCompletedEvent)
Actually, thinking about this further, I think the problem you're trying to solve is a bit more complicated compared to what I did because you're emitting two spans for each activity, one for how long the activity waits for the activity and the other for the actual activity execution. I my case, I only did the latter, which made things much simpler.  If we want to have two spans for each activity execution, with one the parent of the other, then I think you're right that we'll need to store a parent trace context directly in `TaskScheduledEvent`.

2023-01-27 19:13 UTC, jviau commented on src/DurableTask.Core/TaskOrchestrationDispatcher.cs
> +                if (message.Event is TaskCompletedEvent taskCompletedEvent)
Weird that `newActivity.Dispose()` makes `Activity.Current == null`. Disposing an activity should set `Activity.Current` to the recently disposed activity's parent. Is the parent activity (`Activity.Current`) not correctly captured when creating `newActivity`?

2023-01-27 19:15 UTC, jviau commented on src/DurableTask.Core/TaskOrchestrationDispatcher.cs
> +                if (message.Event is TaskCompletedEvent taskCompletedEvent)
> Actually, thinking about this further, I think the problem you're trying to solve is a bit more complicated compared to what I did because you're emitting two spans for each activity, one for how long the orchestration waits for the activity and the other for the actual activity execution. I my case, I only did the latter, which made things much simpler. If we want to have two spans for each activity execution, with one the parent of the other, then I think you're right that we'll need to store a parent trace context directly in TaskScheduledEvent.

Yes, we want two spans. I also recommend you do the same for the go SDK. There is significance to having both, as you can identify gaps in execution- e.g.: if you see a big delta between the start of the `Client` span and the `Server` span, then you probably have a throughput issue and it may be worth investigating.

2023-01-27 19:24 UTC, cgillum commented on src/DurableTask.Core/TaskOrchestrationDispatcher.cs
> +                    TaskScheduledEvent taskScheduledEvent = (TaskScheduledEvent)workItem.OrchestrationRuntimeState.Events.FirstOrDefault(x => x.EventId == taskFailedEvent.TaskScheduledId);
Consider using `LastOrDefault(...)` instead of `FirstOrDefault(...)`. I suspect this will be more efficient in the common case (activity sequences). Also, for defense-in-depth, I wonder if we should do a null check in case we're in a situation where storage is somehow corrupted. It might be better to try and continue the best we can rather than throw a null-ref exception later.

2023-01-27 20:54 UTC, bachuv commented on src/DurableTask.Core/TaskOrchestrationDispatcher.cs
> +                if (message.Event is TaskCompletedEvent taskCompletedEvent)
> Weird that newActivity.Dispose() makes Activity.Current == null. Disposing an activity should set Activity.Current to the recently disposed activity's parent. Is the parent activity (Activity.Current) not correctly captured when creating newActivity?

That was my expectation too, but not what I observed when I stepped through the code. I believe the parent `Activity` is set correctly for `newActivity` because it works fine for the first message in the `NewMessages` list.

2023-01-27 20:57 UTC, bachuv commented
> Did you do a squash merge of `vabachu/suborchupdates` to `cgillum/opentelemetry.`? If so, that would explain this. The squash merge doesn't merge in each individual commit, but a new commit which is all the commits squashed down. If you try and merge those same commits back in, git doesn't know that squashed commit contains them. This isn't a big deal. If you merge in again with another squash commit it will all be fine. If it does bother you, you can use `git rebase -i` on your branch and drop all the commits already contained in the previous PR and only pick your new ones.

Yes, I did a squash merge. Thanks for the explanation! This makes more sense now.

2023-01-31 18:21 UTC, jviau approved these changes

2023-01-31 19:56 UTC, cgillum requested changes
It looks like this PR is reverting a bunch of changes that were made after the PR was initially opened. Does this PR need to be rebased on top of the latest changes from `main`?

2023-01-31 19:56 UTC, cgillum commented on samples/DistributedTraceSample/Program.cs
>              worker.AddTaskOrchestrations(typeof(EventConversationOrchestration));
Is the `FireAndForgetSubOrchestration` supposed to be part of this PR?

2023-01-31 19:58 UTC, cgillum commented
Or maybe there's something wrong with the diff I'm looking at...let me look again using a different diff comparer.

2023-01-31 20:02 UTC, cgillum commented
Weird. The diffs I see on github.dev are very different from the diffs I see on github.com. Not sure why.

2023-01-31 20:09 UTC, cgillum reviewed
Just a couple small things.

2023-01-31 20:09 UTC, cgillum commented on src/DurableTask.Core/TaskOrchestrationDispatcher.cs
> +                    // We immediately publish the activity span for this task by creating the activity and immediately calling Dispose() on it.
This comment no longer makes sense here. It might make more sense to move it into the implementation of `EmitActivityforTaskFinished()`

2023-01-31 20:09 UTC, cgillum commented on src/DurableTask.Core/TaskOrchestrationDispatcher.cs
> +                    // We immediately publish the activity span for this task by creating the activity and immediately calling Dispose() on it.
Same thing for this comment.

2023-01-31 20:09 UTC, cgillum commented on src/DurableTask.Core/TaskOrchestrationDispatcher.cs
> +            scheduledEvent.SetParentTraceContext(parentTraceActivity);
Didn't we already do this a few lines up?

2023-01-31 23:44 UTC, bachuv commented on src/DurableTask.Core/TaskOrchestrationDispatcher.cs
> +            scheduledEvent.SetParentTraceContext(parentTraceActivity);
Yes, this line is supposed to handle the case where `scheduledEvent` is reassigned when `includeParameters` is `false`. I moved this line into the if block now.

2023-01-31 23:55 UTC, cgillum commented on src/DurableTask.Core/TaskOrchestrationDispatcher.cs
> +            scheduledEvent.SetParentTraceContext(parentTraceActivity);
Rather than moving it inside the `if` block and maintaining two different calls, shouldn't we just make this call in one place *after* the `if` block?

2023-01-31 23:56 UTC, cgillum commented on src/DurableTask.Core/TaskOrchestrationDispatcher.cs
> +            scheduledEvent.SetParentTraceContext(parentTraceActivity);
Nevermind, I can see that the way you're doing it now is correct since we're dealing with two `TaskScheduledEvent` objects that get sent to different places.

2023-01-31 23:57 UTC, cgillum approved these changes
:shipit:

2023-02-01 00:05 UTC, merged