Log warning on multiple execution completed events and allow termination to override previous execution completed events
Azure/durabletask pull request #949
Opened 2023-09-05 22:39 UTC by davidmrdavid

Replaces: https://github.com/Azure/durabletask/pull/901/files
From this feedback: https://github.com/Azure/durabletask/pull/901/files#r1316325503

Currently, we throw an exception if we receive multiple `ExecutionCompletedEvent`s. That behavior is a bit too strict because it is possible for multiple `ExecutionCompletedEvent`s to be received at once. For example: when a termination signal arrives at the same time as an orchestrator is requested to continue-as-new.

This PR introduces two changes to this behavior:
(1) Instead of throwing an exception like we do today, we now log a warning notifying the reader that we've found multiple execution completed events and how DTFx is resolving this conflict.

(2) If orchestrator is not in the terminated state and the a new event aims to terminate it, the new event overrides the previously encountered `ExecutionCompletedEvent`; this is because termination should be forceful. In all other cases, we discard the new execution completed event.

2023-09-05 22:52 UTC, cgillum requested changes

2023-09-05 22:52 UTC, cgillum commented on src/DurableTask.Core/OrchestrationRuntimeState.cs
> +                    TraceHelper.Trace(TraceEventType.Warning, "OrchestrationRuntimeState-DuplicateEvent", log);
This uses the old unstructured logging mechanism, which most users will never see. I think we need to instead find a way to use the `LogHelper` class here, perhaps by adding overloads to the methods that call into here which accept a `LogHelper` object.

Also, we'll want to be sure to use a log event that include an `InstanceId` field so that people filtering for events based on the instance ID can find it.

2023-09-05 22:52 UTC, cgillum commented on src/DurableTask.Core/OrchestrationRuntimeState.cs
> +                        // If the new event requests termination, we override the pre-existing execution completed event. This is because termination should be considered to be forceful.
I'm not sure this is the right thing to do. If an orchestration has already completed, then we should let it remain in the completed state. There's no reason to change it and I think it's harmless to drop the terminated event. The only case for replacing the status would be if it's in a `ContinuedAsNew` state and then received a terminate event.

2023-09-05 22:52 UTC, cgillum commented on src/DurableTask.Core/OrchestrationRuntimeState.cs
> +                    var log = $"The orchestration '{this.OrchestrationInstance?.InstanceId ?? ""}' " +
This log message feels a little too verbose. Can we simplify it to something like `$"Ignoring {completedEvent.GetType().Name} event since the orchestration is already in the {orchestrationStatus} state."`.

2023-09-05 23:25 UTC, davidmrdavid commented on src/DurableTask.Core/OrchestrationRuntimeState.cs
> +                        // If the new event requests termination, we override the pre-existing execution completed event. This is because termination should be considered to be forceful.
Fair enough, I've restricted this logic to only applies to the `ContinueAsNew` case.

2023-09-05 23:39 UTC, davidmrdavid commented on src/DurableTask.Core/OrchestrationRuntimeState.cs
> +                    TraceHelper.Trace(TraceEventType.Warning, "OrchestrationRuntimeState-DuplicateEvent", log);
Hmm, I see what you mean. 
My only concern with this request is that the refactoring to bring `LogHelper` here isn't trivial from what I can tell (e.g I can't _just_ add a `LogHelper` parameter `OrchestrationRuntimeState.AddEvent()` because `AddEvent` is public whereas `LogHelper` is internal), and so I worry about growing the scope of this PR.

Would you be willing to track modernizing the logging in this codepath that as a separate work item, or is this a blocker for you? If it's a blocker, I'll go ahead and starting working on it, but first I'm trying to determine my options.

2023-09-05 23:49 UTC, cgillum commented on src/DurableTask.Core/OrchestrationRuntimeState.cs
> +                    TraceHelper.Trace(TraceEventType.Warning, "OrchestrationRuntimeState-DuplicateEvent", log);
A simple, if slightly hackly, solution would be to add an internal method or constructor overload that sets a private `LogHelper` field. if that field is non-null, then we can write the log message. It's probably not worth blocking on this, but at a minimum we should use a `TraceHelper` method that accepts an orchestration instance ID parameter. Otherwise, the logging is going to be pretty unhelpful.

2023-09-18 22:53 UTC, davidmrdavid commented on src/DurableTask.Core/OrchestrationRuntimeState.cs
> +                    var log = $"The orchestration '{this.OrchestrationInstance?.InstanceId ?? ""}' " +
Sure, incorporated this in my next commit.

2023-09-19 00:03 UTC, davidmrdavid commented on src/DurableTask.Core/Logging/EventIds.cs
> +        public const int OrchestrationDebugTrace = 73;
It seemed to me that we were missing a general "debug trace" for logs like this one, so I decided to create one. It did not seem appropriate to create a very specific new category just for this log, so instead I created a more general one.

2023-09-19 00:05 UTC, davidmrdavid commented on src/DurableTask.Core/OrchestrationRuntimeState.cs
> +                    LogHelper?.OrchestrationDebugTrace(this.OrchestrationInstance?.InstanceId ?? "", this.OrchestrationInstance?.ExecutionId ?? "", log);
I did not find a pre-existing loghelper method that fit this case.

2023-09-19 00:06 UTC, davidmrdavid commented on src/DurableTask.Core/OrchestrationRuntimeState.cs
> +                    TraceHelper.Trace(TraceEventType.Warning, "OrchestrationRuntimeState-DuplicateEvent", log);
I took your suggestion to create an internal method that sets a `LogHelper` field.

2023-09-19 00:18 UTC, cgillum approved these changes
:shipit:

2023-09-21 22:04 UTC, cgillum commented on src/DurableTask.Core/OrchestrationRuntimeState.cs
> +                    var log = $"Received new {completedEvent.GetType().Name} event despite the orchestration being already in the {orchestrationStatus} state.";
I'm not a fan of this log change. You're saying we received an event but you're not saying what we're doing with it. The previous log made it clear that we're ignoring the new event.

2023-09-21 22:49 UTC, davidmrdavid commented on src/DurableTask.Core/OrchestrationRuntimeState.cs
> +                    var log = $"Received new {completedEvent.GetType().Name} event despite the orchestration being already in the {orchestrationStatus} state.";
@cgillum: I think there might be some confusion here. The log grows to include whether we decided to ignore the event later on. We don't always ignore the new event, as seen in the snippet below:

https://github.com/Azure/durabletask/blob/5a068aac2bdd2a6dc751be6e57ad5ae2fb939f37/src/DurableTask.Core/OrchestrationRuntimeState.cs#L287-L295

So it's a log message that's created in two parts. First we capture that we're in a situation where we have to make a decision of which ExecutionCompletedEvent to preserve, and we include which one we decide to preserve (the new one or the previous one).

2023-10-04 17:56 UTC, cgillum commented on src/DurableTask.Core/OrchestrationRuntimeState.cs
> +                    var log = $"Received new {completedEvent.GetType().Name} event despite the orchestration being already in the {orchestrationStatus} state.";
I see. In that case it's fine, but I think you need to add a space between the period in the first half of the log and the start of the next sentence.

2023-12-06 01:21 UTC, davidmrdavid commented on src/DurableTask.Core/OrchestrationRuntimeState.cs
> +                    var log = $"Received new {completedEvent.GetType().Name} event despite the orchestration being already in the {orchestrationStatus} state.";
addressed in latest commit: https://github.com/Azure/durabletask/pull/949/commits/c23d3cc18da93e241b94839a69bedfae52292dc1

2023-12-06 01:22 UTC, merged

2024-01-15 08:10 UTC, superLionn commented
Hi team, may I ask the official release time?